### ISSUE TITLE
[Sequencer/RPC] DS repopulation hangs for a long time once complete

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#1003]
If you clear down the data-stream.bin and data-stream.db files from an RPC node then start it again the code repopulates the stream fine, but there is a long delay where it appears that nothing is happening after this has completed.  Eventually the node starts the stage loop again and things continue as normal but the slowness at the end of the population needs looking into as this never used to be a problem.

**Comment by mandrigin** [comment]
fixed by #1004
