### ISSUE TITLE
[Metrics] Expose last checked L1 block as a prometheus metric

### ISSUE THREAD

**Issue by sebastiendan** [0xPolygon/cdk-erigon#1005]
# Rationale

Checking that the L1 Syncer is not too far behind is quite important to ensure l1-l2 operations can work properly.

# Implementation

Currently, the last checked block is exposed in `Saving L1 syncer progress` logs' event attributes.

**Comment by sebastiendan** [comment]
@mandrigin We're using an internal tool for monitoring that is primarily based on generating Prometheus metrics from RPC commands we execute on specific nodes. If that makes sense to you, you could expose the last checked l1 block as an RPC command directly, or in addition to exposing it as a metric.

**Comment by Sharonbc01** [comment]
Hi @mandrigin can you please assign this issue re alerting always nice to have thanks.
