### ISSUE TITLE
[RPC] add zkevm_getProof

### ISSUE THREAD

**Issue by pgebheim** [0xPolygon/cdk-erigon#1010]
# Rationale

For applications that need to build a light client to a CDK/zkEVM they need some way to prove membership/nonmembership within the Poseidon SMT similar to how eth_getProof works for a Keccak MPT. This could be useful for integrations with IBC (such as union is working on) and for ENS.

## Request

Add custom RPC endpoont `zkevm_getProof`. This should take the same inputs, and produce a similar output payload to eth_getProof replacing SHA3 with Poseidon where appropriate. For instance, `storageHash` and `accountProof` will return data in appropriate to the Poseidon SMT state format.

**Comment by cffls** [comment]
WIP branch: https://github.com/0xPolygonHermez/cdk-erigon/tree/feat/smt_get_proof
Design doc: https://hackmd.io/mZJIAVWXS9GtARxaIBNsbA

**Comment by hexoscott** [comment]
closing as the code is now merged
