### ISSUE TITLE
[Sequencer, RPC] for witness replace "running opcodes after OOG" to tailored solutions for each such opcode

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#1012]
Currently we have this code: https://github.com/0xPolygonHermez/cdk-erigon/blob/569ec3be7c9067942c3d402a164596d20da88fe1/core/vm/interpreter_zkevm.go#L216

That code just executes opcodes even if they are out of gas.

That is done so the witness has all necessary info.

That leads to unfortunate consequences when fuzzed (like Erigon trying to make a 400GB size hex-string).

Instead, we should just add a tailored solution for each opcode.

The list of opcodes and what is needed to be added to the witness is here:  https://hackmd.io/MEmJVs0AS1Owpwug6q5Eqg?view

**Comment by kstoykov** [comment]
Currently the code on line 216 is executed only for opcodes specified here: https://hackmd.io/MEmJVs0AS1Owpwug6q5Eqg?view (line 194). In addition to that the opcode that is executed on line 216 is the last non-executed opcode that has triggered an error during execution.

**Comment by hexoscott** [comment]
Closing this one down as we now have code to handle all of these scenarios nicely.  Last week we boxed off the last of the problems with memory issues in an OOG scenario related to this.
