### ISSUE TITLE
[Sequencer] Halt on batch mismatch

### ISSUE THREAD

**Issue by rafael-genes** [0xPolygon/cdk-erigon#1025]
#### System information

Erigon version: hermeznetwork/cdk-erigon:acceptance-2.0.0-beta17-a61220d-amd64

OS & Version: docker

Chain/Network: Bali

#### Expected behaviour
When you set the param zkevm.sequencer-halt-on-batch-number, stop on previous batch and halt on specifed batch nuber.

#### Actual behaviour
Config with batch 69326, show logs with halt on batch 69325 and sequencer's rpc returns zkevm_batchNumber 69324. All should be aligned.

#### Steps to reproduce the behaviour
Start sequencer with config zkevm.sequencer-halt-on-batch-number: 69326

**Comment by V-Staykov** [comment]
This is now fixed on latest zkevm and on 2.0.0-beta17
