### ISSUE TITLE
Required IOPs on mainnet

### ISSUE THREAD

**Issue by Sharonbc01** [0xPolygon/cdk-erigon#1029]
SPEC v-team need to ensure there is sufficient IPOS for mainnet to support the deployment of sequencer to mainnet

**Comment by Sharonbc01** [comment]
@rafael-genes confirmed the same configuration applied to cardona will be applied to mainnet. Keeping this ticket open in case load test reveals any need to up the IOPs next week.

**Comment by giskook** [comment]
Could you pls share us the disk configuration? Especially the IOPS and Throughput? many thanks.
