### ISSUE TITLE
[Datastream] Some `batchStart` entries in the Cardona datastream have `forkId` not set

### ISSUE THREAD

**Issue by V-Staykov** [0xPolygon/cdk-erigon#1036]
Chain/Network:  Cardona

#### Expected behaviour
All `batchStart` entries should have forkid set.

#### Actual behaviour
On Cardona stream `datastream.cardona.zkevm-rpc.com:6900` some blocks have `forkId` of 0. Examples are the batch starts for batches: 7, 49

These coincide with empty batches (no blocks), so this may be connected

**Comment by hexoscott** [comment]
This is now fixed, caused by us not writing the fork for an empty batch.  We now fall back to the previous batch fork id when populating the stream.
