### ISSUE TITLE
Sequence sender batch mismatch 

### ISSUE THREAD

**Issue by rafael-genes** [0xPolygon/cdk-erigon#1058]
#### System information

Erigon version: hermeznetwork/cdk-erigon:v2.0.0-beta17-amd64
OS & Version: docker
Chain/Network: Bali

#### behaviour
Sequence sender syncs from the sequencer's datastream and perform the sanity checks from the main RPC. After working several minutes with that configuration, it ends with a fatal error.

number of blocks in batch 69491 (77) does not match the number of blocks in the batch from the RPC (76)

We regenerate datastream on sequencer just before the procedure.

**Comment by mandrigin** [comment]
Turns out seq sender didn’t check if the batch was closed, so the issue was requesting the WIP batch before it fully was synced by RPC. seq sender restored.
