### ISSUE TITLE
[RPC] zkevm_estimateCounters needs more fields than eth_estimateGas

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#1065]
![image](https://github.com/user-attachments/assets/b3674501-f881-4d86-bd32-4bac04080f7e)

In the image above you can see the estimate gas call works just fine with only an input but the estimate counters doesn't.  We should support this in estimate counters.

**Comment by V-Staykov** [comment]
For the coutners we need the v,r,s of the transaction. It is used when calculating the RLP counters.

**Comment by hexoscott** [comment]
Can we substitute in some fake values for this just for counters?

**Comment by V-Staykov** [comment]
There might be some case that repeats in the majority of cases, that we can use, but I don't know it. In either case, the ecRecover counters is a bit complex and not calculating it will probably always give us some error margin.

**Comment by tclemos** [comment]
All the estimate methods in the legacy node use the `unsigned` tx execution flow, which basically provides default information to the executor in case the parameter is not provided. 

The way we execute the TX for the `estimateGas` is almost the same as we do for the `estimateCounters`, the only difference is exactly a flag to specify if the execution should take counters into account;
- execution used by estimateGas: https://github.com/0xPolygonHermez/zkevm-node/blob/741b9b06d2faf6f855109805fcc797096a8af34f/state/transaction.go#L1038C2-L1056C3
- execution used by estimateCounters: https://github.com/0xPolygonHermez/zkevm-node/blob/741b9b06d2faf6f855109805fcc797096a8af34f/state/transaction.go#L530-L550

The default sender we use is `0x1111111111111111111111111111111111111111`
- https://github.com/0xPolygonHermez/zkevm-node/blob/741b9b06d2faf6f855109805fcc797096a8af34f/state/state.go#L24-L25

Here are the defaults when converting estimate parameters to a TX:
- https://github.com/0xPolygonHermez/zkevm-node/blob/741b9b06d2faf6f855109805fcc797096a8af34f/jsonrpc/types/types.go#L192-L238
