### ISSUE TITLE
Prepare upgrade transaction & any required timelock for Cardona fork 11

### ISSUE THREAD

**Issue by Sharonbc01** [0xPolygon/cdk-erigon#1066]

**Comment by Sharonbc01** [comment]
Hi @krlosMata as discussed today is is required for planned upgrade on Sept 12 please.

**Comment by krlosMata** [comment]
done.
New rollup type is 6.
All its info can be checked in https://sepolia.etherscan.io/address/0x32d33d5137a7cffb54c5bf8371172bcec5f310ff#readProxyContract#F27 with `rollupTypeID = 6`

**Comment by Sharonbc01** [comment]
Thanks @krlosMata I will close this issue. 

cc: @rekibnikufesin @rafael-genes
