### ISSUE TITLE
ProviderError too many arguments, want at most 1

### ISSUE THREAD

**Issue by omnifient** [0xPolygon/cdk-erigon#1077]
Someone deploying their smart contracts on Polygon ZkEVM reported an error during their deployment process using https://zkevm-rpc.com/ 

The error that's surfaced back by hardhat is `ProviderError too many arguments, want at most 1`. 
After some searching, it seems like it might be related to [this](https://github.com/NomicFoundation/hardhat/issues/4010) which in turn is referenced by [eth_estimateGas Errors occur on other chains](https://github.com/NomicFoundation/hardhat/issues/4332) and [EstimateGas support the latest hardhat](https://github.com/XinFinOrg/XDPoSChain/pull/329).

They were able to deploy on other chains without issues, including X Layer. They were also able to deploy without issues on ZkEVM using the legacy rpc (https://rpc-legacy.zkevm-rpc.com/), which hints that the problem is caused by the Erigon client.

Unfortunately the [deployment process](https://github.com/dolomite-exchange/dolomite-margin-modules/blob/master/packages/deployment/src/deploy/ecosystems/deploy-dolomite-ecosystem.ts) is not simple, so the error could be caused by any endpoint.
One interesting data point is that the error did not cause the [the deployment transaction](https://zkevm.polygonscan.com/tx/0xd5226727d539e7a7c76fbd59b9ebe0324d302405422f5e8c8b180b5f66f6a2d4) to fail, so it suggests being in a read-only endpoint?

[Internal slack discussion link](https://0xpolygon.slack.com/archives/C04QVP1584C/p1724950111760649)

**Comment by praetoriansentry** [comment]
I created #1078  based on looking into this issue. I've confirmed that the RPCs used during a trivial hard hat deployment work fine. I can't definitively say that #1078  caused their issue. I'd be surprised if they have a dependency on a non-standard parameter in `eth_getTransactionByHash`, but it's possible. Either way we should address the discrepancy and review the RPCs for other discrepancies that could cause issues like this.

**Comment by V-Staykov** [comment]
#1078 is now fixed

**Comment by omnifient** [comment]
thanks @V-Staykov any idea when will this get pushed into the mainnet nodes?

**Comment by V-Staykov** [comment]
No. Maybe with release 19.
