### ISSUE TITLE
Discard buggy transactions

### ISSUE THREAD

**Issue by ignasirv** [0xPolygon/cdk-erigon#1096]
# Rationale
We have found a bug at the rom from this issue: https://github.com/0xPolygonHermez/cdk-erigon/issues/1073
The bug will be fixed for fork 10, 11 and so on, but we will need to reject from Erigon's side those transactions that trigger the bug at fork 9 :confused:
The transactions are those calls (not deploy) where the last opcode of the calldata is a PUSH or calls calling a contract where the last opcode of the bytecode is a PUSH

**Comment by mandrigin** [comment]
Related to #1073

**Comment by hexoscott** [comment]
Opened this https://github.com/0xPolygonHermez/cdk-erigon/pull/1159 to help stop this from executing.  A local test with the same code example from #1073 does return an "invalid code" response when attempting to call the contract.

**Comment by ignasirv** [comment]
It's important to discard this transaction so it is not sent to executor

**Comment by Sharonbc01** [comment]
Hi @ignasirv this bug was to be fixed for fork 10, 11. Can this issue now be closed now?

**Comment by ignasirv** [comment]
Yes!
