### ISSUE TITLE
[Sequence-Sender] Nonce issues while working on parallel mode

### ISSUE THREAD

**Issue by ToniRamirezM** [0xPolygon/cdk-erigon#1127]
It has been detected on Bali that enabling the parallel sending to L1 in the sequence sender makes it get to a point where nonces are not properly handled and so it can properly send sequences due to "nonce too low" errors.

Currently this can be avoided by disabling parallel mode (limit txs to 1), but this should be fixed before going to mainnet.

**Comment by Sharonbc01** [comment]
Hi @ToniRamirezM can this issue be closed now please?

**Comment by ToniRamirezM** [comment]
Yes, fix has been deployed and validated on Bali. Also the code has been updated in CDK's seq-sender.

**Comment by ToniRamirezM** [comment]
It looks like problems persist. I will review again the issue taking into account eth-tx-manager logic around the nonce as I think this is related.

**Comment by ToniRamirezM** [comment]
With the latest fix, deployed, on september 20 the issue looks like has been fixed. All pending batches have been properly sequenced in Cardona.
