### ISSUE TITLE
[zero - Cancun] - Remove unecessary Cancun bits from cdk-erigon

### ISSUE THREAD

**Issue by Nashtare** [0xPolygon/cdk-erigon#1133]
Similarly to the Napoli upgrade on Polygon PoS, we don't need inclusion of EIP-4788 (Beacon Roots) or EIP-4844 (sharding).
In particular, the former affects block pre-state execution and should be disabled before attempting to prove type2 cdk-based chains with Zero prover.

cc @cffls @temaniarpit27

**Comment by cffls** [comment]
Confirmed that EIP-4788 [won't be enabled](https://github.com/0xPolygonHermez/cdk-erigon/blob/449d5e249271e02775cc4acfb69ba062fc3e766e/eth/ethconsensusconfig/config.go#L124) when `TerminalTotalDifficulty` isn't provided in chain spec, e.g. [this one](https://github.com/0xPolygon/kurtosis-cdk/blob/cdk-erigon-cancun/templates/cdk-erigon/chainspec.json).

**Comment by cffls** [comment]
This [PR](https://github.com/0xPolygonHermez/cdk-erigon/pull/1147) removes opcodes and precompile from EIP-4844.

**Comment by cffls** [comment]
Closing this as the issues have be addressed.
