### ISSUE TITLE
Limbo mode panic `requested batch 6820 while the network is already on 6821`

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#1135]
After getting some OOC errors in limbo mode, my sequencer seemed to stop:

![image](https://github.com/user-attachments/assets/a8f53f41-3a53-4926-a0e5-5e58c3ee825e)

After restarting the sequencer, I essentially got the same error, but with a different batch number:

![image](https://github.com/user-attachments/assets/3e211765-7bba-4467-b23d-9699b9d69583)

**Comment by kstoykov** [comment]
@praetoriansentry what version of the node have  you been using?

**Comment by kstoykov** [comment]
Fixed in: https://github.com/0xPolygonHermez/cdk-erigon/pull/1129
