### ISSUE TITLE
Regression test CDK Erigon with integrated banana rollback feature code changes 

### ISSUE THREAD

**Issue by Sharonbc01** [0xPolygon/cdk-erigon#1141]
Now the Banana rollback feature [code changes](https://github.com/0xPolygonHermez/cdk-erigon/pull/894) are merged Gateway FM to perform regression testing.

For reference see [Banana Specifications](https://hackmd.io/O4t3Xvj9TIydY9UsXfXHiA?view#Implications12)

**Comment by Sharonbc01** [comment]
@hexoscott you were looking after this. Can this issue be closed now?

**Comment by hexoscott** [comment]
I'd say so yes, given we're about to merge in 2.60 changes into zkevm that will invalidate any of this testing anyway and it will need repeating.
