### ISSUE TITLE
[zero zkEVM] - Revert encoding change back to RLP

### ISSUE THREAD

**Issue by Nashtare** [0xPolygon/cdk-erigon#1148]
Zero zkEVM already supports RLP encoding to support vanilla MPTs for Txn / Receipt tries without this being a real bottleneck, it'd be best to remain consistent and reuse the regular MPT format for these 2 tries as well for the type2.

**Comment by cffls** [comment]
@Nashtare is this regarding [zero tracer](https://github.com/0xPolygonHermez/cdk-erigon/blob/zkevm/eth/tracers/native/zero.go) or the [trie roots](https://github.com/0xPolygonHermez/cdk-erigon/blob/d6f70f1502b14d48e55cd5082b66c9eaad3eb0ae/core/blockchain_zkevm.go#L204-L205) in the block header?

The implementations of tx/receipt encoding are the same in both [cdk-erigon](https://github.com/0xPolygonHermez/cdk-erigon/blob/zkevm/eth/tracers/native/zero.go#L297-L315) and [type1 erigon](https://github.com/0xPolygonZero/erigon/blob/feat/zero/eth/tracers/native/zero.go#L297-L315). If we are talking about zero tracer, do you mean to change the encoding in both places?

If we are talking about the trie roots of txns and receipts in the block header, I believe they are calculated the same way as type 1.

**Comment by cffls** [comment]
As discussed with @Nashtare , the tx hash function in question was [`ComputeL2TxHash`](https://github.com/0xPolygonHermez/cdk-erigon/blob/df6709f065b59a299e893b30db714b82b8a0e41e/zk/tx/tx.go#L426-L432).  
This function affects:
   1. L2 block info tree
   2. Datastream
   3. zkevm_* rpc
   
`1` will be disabled in Normalcy HF, `2` is agnostic to zero prover, and `3` won't be used by zero prover. Therefore, this is a non-issue once https://github.com/0xPolygonHermez/cdk-erigon/pull/1374 is merged.

**Comment by Stefan-Ethernal** [comment]
It was addressed through #1374.
