### ISSUE TITLE
[DS] Empty batches are stored with Fork 0

### ISSUE THREAD

**Issue by tclemos** [0xPolygon/cdk-erigon#1163]
while syncing Bali debugging, during the state_batches, it is possible to see that batches `0x25`, `0x46`, and `0xaf` have ForkID as 0x0.

@hexoscott investigated the DS, and it looks like the node is assuming `Fork 0` when the Batch is `empty`.

Even though the state is not affected by this wrong fork information because the batch is empty, it negatively affects a feature under development that maps the fork batch interval.

**Comment by hexoscott** [comment]
handled in #1164 closing for now and can re-open if needed
