### ISSUE TITLE
Disconnect between `txpool_status` and `txpool_content`

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#1165]
My node seems to be in a weird state after some limbo unwinds where the `txpool_status` indicates that there are `0xb` transactions that are queued, but when I look for those transactions in the `txpool_content` they do not appear:
![image](https://github.com/user-attachments/assets/4615ba3b-95ff-4f89-a8bd-963b61e3a114)

This is occurring with `hermeznetwork/cdk-erigon:v2.0.0-beta18`

**Comment by V-Staykov** [comment]
I am unable to reproduce this. Content and status seem to match for me after I simulated some limbo transactions. Can you reproduce it under certain conditions and share that?

**Comment by praetoriansentry** [comment]
I've had it occur several times, but the reproduction is going to be complicated because it's usually from fuzzing. I.e. usually the tx pool is filled with several thousand transactions when limbo is triggered.

**Comment by V-Staykov** [comment]
And it is for sure after limbo? I ask because the virtual counters should make the limbo a very rare occurance.

**Comment by Sharonbc01** [comment]
Hi @praetoriansentry is this issue still valid or can this be closed? Thanks

**Comment by praetoriansentry** [comment]
It's still valid. I saw it again today while testing beta26

**Comment by Sharonbc01** [comment]
Okay will add to RC1 milestone

**Comment by afa7789** [comment]
Hey John,
I attempted to replicate this by simulating multiple transactions with public accounts. I topped them up locally and created a script to simulate the transactions, listening to the cast rpc for status and content. However, I wasn't able to find the same content/status disparity that you highlighted in the issue.

Could you still replicate this on your side? If so, could you provide additional steps or materials to help me reproduce it?

You can find the scripts I used here:

https://gist.github.com/afa7789/a4bf884caa013d5026b803abc76cc4fd

If you have any questions, feel free to reach out.

Here’s the order in which I used the scripts:

1. `go run cmd/cdk-erigon/main.go --config="hermezconfig-dev-sequencer.yaml"`
2. `./cast_rpc.sh`
3. `python3 simulate_transactions.py`
4. `./john_report.sh`

**Comment by Sharonbc01** [comment]
FYI @praetoriansentry

**Comment by mandrigin** [comment]
It's been a month, I will close it. @praetoriansentry feel free to reopen if you see it again.
