### ISSUE TITLE
Slow performance after sending many txs

### ISSUE THREAD

**Issue by xavier-romero** [0xPolygon/cdk-erigon#1190]
Running locally on Kurtosis with these images:

- "image": "hermeznetwork/zkevm-prover:v7.0.0-fork.11"
- "image": "hermeznetwork/cdk-erigon:v2.0.0-beta18"
- "image": "hermeznetwork/zkevm-sequence-sender:v0.2.0",
-  "image": "hermeznetwork/zkevm-aggregator:v0.0.4",

After sending as many txs as the pool can receive (30000) with this test:
`python3 tool_sc_chaos_monkey.py -p kurtosis -s 50 -r 100 -t 1000  -d 4096 -e 100`

The processing becomes really slow, at a pace of 2 transactions per second.
![image](https://github.com/user-attachments/assets/728b01dc-463b-436a-a70d-6a5da495dd88)

Even when the block time remains stable, the numbers of txs per blocks keeps going down, so far I saw that from 12 to 11, then to 10, etc, right now is 7 txs per block, and decreasing.
The system has plenty of RAM and CPU available, and the sequencer is not limited.

Got the heap and profile for 2 points in time.
- [heap.gz](https://github.com/user-attachments/files/17040670/heap.gz)
- [heap2.gz](https://github.com/user-attachments/files/17040672/heap2.gz)
- [profile.gz](https://github.com/user-attachments/files/17040674/profile.gz)
- [profile2.gz](https://github.com/user-attachments/files/17040676/profile2.gz)

**Comment by xavier-romero** [comment]
Same instance, same system, same pool, same sequencer, same kind of pending txs, the number of txs per block keeps decreasing.

![image](https://github.com/user-attachments/assets/c4aa0c49-3c8e-4e4f-b0f0-b6d9faa72a56)

**Comment by xavier-romero** [comment]
It slows down reducing the number of txs per block... it evens produces an empty block (with lot of pending txs in the pool), but just after that empty block it gets back to work and starts operating normally again... but slowing down until it reaches 0 txs/block again and the process repeats once and once again.

![image](https://github.com/user-attachments/assets/46afd388-561b-4921-9f4c-c2a4f92fc645)

**Comment by V-Staykov** [comment]
I see the counters take a lot of time. We did optimize this quite a lot. But it still shouldn't lead to this kind of problem. Do the logs show a lot of queued txs in the pool? I am thinking is the pool full and getting txs from it slow, or is the putting txs in the pool slow?

**Comment by xavier-romero** [comment]
pool size is shown in the top right
this situation/screenshots are AFTER sending all txs, so there are no more incoming txs during this issue, just the pool

**Comment by xavier-romero** [comment]
![image](https://github.com/user-attachments/assets/2d3ae786-eba8-4378-bf11-0f40eaf17ddd)

after all this Im sending some more txs, for example simple eoa transfers... its closing blocks with just 1 EOA tx
profiles attached

- [heap3.gz](https://github.com/user-attachments/files/17041680/heap3.gz)
- [profile3.gz](https://github.com/user-attachments/files/17041681/profile3.gz)

**Comment by xavier-romero** [comment]
[sequencer.log.gz](https://github.com/user-attachments/files/17041825/sequencer.log.gz)

Full sequencer logs attached

**Comment by V-Staykov** [comment]
I can't reproduce it with normal send transactions. The test you use seems to send some infinite loop transactions. Seeing the logs where all counters overflow by orders of magnitude. Can you send me the test script?

**Comment by xavier-romero** [comment]
Used the tool mentioned in first post

> `python3 tool_sc_chaos_monkey.py -p kurtosis -s 50 -r 100 -t 1000 -d 4096 -e 100`

From the repo you already know (though):

> https://github.com/xavier-romero/eth-bench

**Comment by V-Staykov** [comment]
Okay it seems this is spamming different transactions - some bigger, some smaller. We also get the occasional 1 tx overflowing the coutners and that is why we produce an empty block. It seems normal to me to get different amount of transactions per block in tis case. Also I sometimes get 20, 100, then a few times 7 or 8.

Do you experience a trending lower transactions per block?

**Comment by xavier-romero** [comment]
> Do you experience a trending lower transactions per block?

YES, I explained the experienced trending lower transactions per block in the issue, illustrating with a screenshot.

-   _Even when the block time remains stable, the numbers of txs per blocks keeps going down, so far I saw that from 12 to 11, then to 10, etc, right now is 7 txs per block, and decreasing._


And on the first comment I remarked that trend again:

- _Same instance, same system, same pool, same sequencer, same kind of pending txs, the number of txs per block keeps decreasing._


And again illustrated with a screenshot.
@mandrigin 

.

> It seems normal to me to get different amount of transactions per block in tis case.

And just for my understanding, as per your words, having thousands of pendint txs on the pool and closing block after block with just 21000 gas (1 simple tx) is a normal behavior then when at some previous point you sent an infinite loop? Just asking here, you're the expert :-)

**Comment by V-Staykov** [comment]
If we have 1 transaction with 21k gas and the second tx we got overflows coutners, the block could be left with just 1 tx and 21k in it. This is a valid case with our current implementation. 

As for the trends I know you mentioned it, but the screenshots you showed are for just a couple of transactions.I to get a trend low for 30-40 blocks, but then get a spike to sometimes 100 or 200 txs. If the script sends big transactions for some time and then small ones - it would be normal to see this.

 I haven't looked too closely what kinds of transactions are being sent, but it seems to me they are several ones and soem of them overflow coutners all by themselves as well.

**Comment by V-Staykov** [comment]
Here is an example
```
[INFO] [09-18|12:31:46.219] [5/13 Execution] Finish block 242 with 13 transactions... 
[INFO] [09-18|12:31:46.314] [5/13 Execution] Finish block 243 with 14 transactions... 
[INFO] [09-18|12:31:46.412] [5/13 Execution] Finish block 244 with 14 transactions... 
[INFO] [09-18|12:31:46.504] [5/13 Execution] Finish block 245 with 14 transactions... 
[INFO] [09-18|12:31:46.595] [5/13 Execution] Finish block 246 with 14 transactions... 
[INFO] [09-18|12:31:46.693] [5/13 Execution] Finish block 247 with 14 transactions... 
[INFO] [09-18|12:31:46.783] [5/13 Execution] Finish block 248 with 14 transactions... 
[INFO] [09-18|12:31:50.137] [5/13 Execution] Finish block 249 with 14 transactions... 
[INFO] [09-18|12:31:50.231] [5/13 Execution] Finish block 250 with 11 transactions... 
[INFO] [09-18|12:31:50.322] [5/13 Execution] Finish block 251 with 11 transactions... 
[INFO] [09-18|12:31:50.412] [5/13 Execution] Finish block 252 with 11 transactions... 
[INFO] [09-18|12:31:50.506] [5/13 Execution] Finish block 253 with 11 transactions... 
[INFO] [09-18|12:31:50.596] [5/13 Execution] Finish block 254 with 11 transactions... 
[INFO] [09-18|12:31:50.687] [5/13 Execution] Finish block 255 with 11 transactions... 
[INFO] [09-18|12:31:50.781] [5/13 Execution] Finish block 256 with 11 transactions... 
[INFO] [09-18|12:31:50.877] [5/13 Execution] Finish block 257 with 11 transactions... 
[INFO] [09-18|12:31:50.974] [5/13 Execution] Finish block 258 with 11 transactions... 
[INFO] [09-18|12:31:51.071] [5/13 Execution] Finish block 259 with 11 transactions... 
[INFO] [09-18|12:31:51.162] [5/13 Execution] Finish block 260 with 11 transactions... 
[INFO] [09-18|12:31:51.254] [5/13 Execution] Finish block 261 with 11 transactions... 
[INFO] [09-18|12:31:51.357] [5/13 Execution] Finish block 262 with 11 transactions... 
[INFO] [09-18|12:31:51.448] [5/13 Execution] Finish block 263 with 11 transactions... 
[INFO] [09-18|12:31:51.541] [5/13 Execution] Finish block 264 with 11 transactions... 
[INFO] [09-18|12:31:51.632] [5/13 Execution] Finish block 265 with 11 transactions... 
[INFO] [09-18|12:31:51.725] [5/13 Execution] Finish block 266 with 11 transactions... 
[INFO] [09-18|12:31:51.817] [5/13 Execution] Finish block 267 with 11 transactions... 
[INFO] [09-18|12:31:51.924] [5/13 Execution] Finish block 268 with 11 transactions... 
[INFO] [09-18|12:31:52.018] [5/13 Execution] Finish block 269 with 11 transactions... 
[INFO] [09-18|12:31:52.110] [5/13 Execution] Finish block 270 with 11 transactions... 
[INFO] [09-18|12:31:52.206] [5/13 Execution] Finish block 271 with 11 transactions... 
[INFO] [09-18|12:31:52.304] [5/13 Execution] Finish block 272 with 11 transactions... 
[INFO] [09-18|12:31:52.395] [5/13 Execution] Finish block 273 with 11 transactions... 
[INFO] [09-18|12:31:52.489] [5/13 Execution] Finish block 274 with 11 transactions... 
[INFO] [09-18|12:31:52.578] [5/13 Execution] Finish block 275 with 10 transactions... 
[INFO] [09-18|12:31:52.675] [5/13 Execution] Finish block 276 with 11 transactions... 
[INFO] [09-18|12:31:52.783] [5/13 Execution] Finish block 277 with 11 transactions... 
[INFO] [09-18|12:31:52.881] [5/13 Execution] Finish block 278 with 11 transactions... 
[INFO] [09-18|12:31:52.973] [5/13 Execution] Finish block 279 with 11 transactions... 
[INFO] [09-18|12:31:53.069] [5/13 Execution] Finish block 280 with 11 transactions... 
[INFO] [09-18|12:31:53.159] [5/13 Execution] Finish block 281 with 11 transactions... 
[INFO] [09-18|12:31:56.512] [5/13 Execution] Finish block 282 with 17 transactions... 
[INFO] [09-18|12:31:56.621] [5/13 Execution] Finish block 283 with 34 transactions... 
[INFO] [09-18|12:31:56.977] [5/13 Execution] Finish block 284 with 39 transactions... 
[INFO] [09-18|12:31:57.089] [5/13 Execution] Finish block 285 with 39 transactions... 
[INFO] [09-18|12:31:57.445] [5/13 Execution] Finish block 286 with 34 transactions... 
[INFO] [09-18|12:31:57.561] [5/13 Execution] Finish block 287 with 40 transactions... 
```
```

[INFO] [09-18|12:32:28.346] [5/13 Execution] Finish block 576 with 1 transactions... 
[INFO] [09-18|12:32:28.376] [5/13 Execution] Finish block 577 with 1 transactions... 
[INFO] [09-18|12:32:28.398] [5/13 Execution] Finish block 578 with 1 transactions... 
[INFO] [09-18|12:32:28.424] [5/13 Execution] Finish block 579 with 1 transactions... 
[INFO] [09-18|12:32:28.497] [5/13 Execution] Finish block 580 with 1 transactions... 
[INFO] [09-18|12:32:28.521] [5/13 Execution] Finish block 581 with 1 transactions... 
[INFO] [09-18|12:32:28.594] [5/13 Execution] Finish block 582 with 1 transactions... 
[INFO] [09-18|12:32:28.615] [5/13 Execution] Finish block 583 with 1 transactions... 
[INFO] [09-18|12:32:28.682] [5/13 Execution] Finish block 584 with 1 transactions... 
[INFO] [09-18|12:32:28.702] [5/13 Execution] Finish block 585 with 1 transactions... 
[INFO] [09-18|12:32:28.721] [5/13 Execution] Finish block 586 with 1 transactions... 
[INFO] [09-18|12:32:28.739] [5/13 Execution] Finish block 587 with 1 transactions... 
[INFO] [09-18|12:32:28.759] [5/13 Execution] Finish block 588 with 1 transactions... 
[INFO] [09-18|12:32:28.780] [5/13 Execution] Finish block 589 with 1 transactions... 
[INFO] [09-18|12:32:28.805] [5/13 Execution] Finish block 590 with 1 transactions... 
[INFO] [09-18|12:32:28.824] [5/13 Execution] Finish block 591 with 1 transactions... 
[INFO] [09-18|12:32:28.846] [5/13 Execution] Finish block 592 with 1 transactions... 
[INFO] [09-18|12:32:28.867] [5/13 Execution] Finish block 593 with 1 transactions... 
[INFO] [09-18|12:32:28.889] [5/13 Execution] Finish block 594 with 1 transactions... 
[INFO] [09-18|12:32:28.914] [5/13 Execution] Finish block 595 with 1 transactions... 
[INFO] [09-18|12:32:28.934] [5/13 Execution] Finish block 596 with 1 transactions... 
[INFO] [09-18|12:32:28.957] [5/13 Execution] Finish block 597 with 1 transactions... 
[INFO] [09-18|12:32:28.984] [5/13 Execution] Finish block 598 with 1 transactions... 
[INFO] [09-18|12:32:29.011] [5/13 Execution] Finish block 599 with 1 transactions... 
[INFO] [09-18|12:32:29.082] [5/13 Execution] Finish block 600 with 1 transactions... 
[INFO] [09-18|12:32:51.438] [5/13 Execution] Finish block 601 with 0 transactions... 
[INFO] [09-18|12:32:51.554] [5/13 Execution] Finish block 602 with 63 transactions... 
[INFO] [09-18|12:32:51.697] [5/13 Execution] Finish block 603 with 53 transactions... 
[INFO] [09-18|12:32:51.827] [5/13 Execution] Finish block 604 with 48 transactions... 
[INFO] [09-18|12:32:51.937] [5/13 Execution] Finish block 605 with 45 transactions... 
[INFO] [09-18|12:32:52.046] [5/13 Execution] Finish block 606 with 41 transactions... 
[INFO] [09-18|12:32:52.157] [5/13 Execution] Finish block 607 with 35 transactions... 
[INFO] [09-18|12:32:52.526] [5/13 Execution] Finish block 608 with 36 transactions... 
[INFO] [09-18|12:32:52.637] [5/13 Execution] Finish block 609 with 35 transactions... 
[INFO] [09-18|12:32:52.741] [5/13 Execution] Finish block 610 with 34 transactions... 
[INFO] [09-18|12:32:53.096] [5/13 Execution] Finish block 611 with 34 transactions... 
```

The ones with 1 tx in them seem to fail exactly like I said in the previous comment - 1 tx goes in and the second overflows counters, so we remove it and close the block.

**Comment by xavier-romero** [comment]
So, I can imagine we have something like that in the pool (let me think of it as a stack):

```
- 1_valid_simple_eoa_transfer_21000_gas
- 2_overflow_tx
- 3_valid_simple_eoa_transfer_21000_gas
- 4_valid_simple_eoa_transfer_21000_gas
- 5_valid_simple_eoa_transfer_21000_gas
```

We pick tx 1 for block 1000, ok. Then we pick tx 2, and counters overflow, oks. The block 1000 is closed with 1 tx, oks.
Then for block 1001, my understanding is that we firstly pick tx 2 (which now is the first in the stack) and as it does NOT fit on the entire block, it will be discarded right? So now txs 3, 4, 5, etc should be fitted into block 1001, right?
Instead of that, block 1001 is closed again with just 1 tx. How is that?

**Comment by xavier-romero** [comment]
Discussing in Slack we got to the conclusion that it could be that a tx is only discarded when it does not fit a batch, and that this tx is tried for every block of the current batch until we reach the next one and is finally discarded. That could explain the issue.
So just 1 overflow tx in the pool is enough to make all blocks of the current batch to be closed with 1 tx each.

**Comment by V-Staykov** [comment]
In this case we would make: block 1000 with 1 tx, block 1001 - empty, block 1002 with  txs 3,4,5

In order to know if the coutners overflow, we execute the transaction. If they overflow, we rollback the transaction and close the block. If the transaction overflows a whole block single handedly it is being discarded from the pool.

**Comment by xavier-romero** [comment]
> In this case we would make: block 1000 with 1 tx, block 1001 - empty, block 1002 with txs 3,4,5

That's not what happening, as you can see on the screenshots all blocks one after another are closed with just 1 tx !

**Comment by V-Staykov** [comment]
Okay, let me check if we are retrying the same overflowing transaction for some reason.

There might be a case where the pool does a normal reordering after each added transaction to a block and it does put a big transaction after a small one that was previously behind several times.

Either way, it is an issue with the pool not accomodating coutners currently and it is a problem that needs a lot of attention. We are already discussing how to ooptimize block building for coutners.

**Comment by xavier-romero** [comment]
Also, from my total lack of knowledge of the internal complexity of the pool:

> In this case we would make: block 1000 with 1 tx, block 1001 - empty, block 1002 with txs 3,4,5

Why block 1001 would be empty instead of setting txs 3, 4 and 5?
Would it make sense to include 3, 4 and 5 directly on block 1000 after we delayed tx 2? (As long as they're not from the same sender)

**Comment by V-Staykov** [comment]
It would be great, but we don't have this functionality yet. We are talking about doing better on the pool to have in mind counters as well, but it will require a lot of effort.

Currently we just get them ordered byt the pool and try to add them in the same order. If coutners overflow, we stop there and close the block, then continue from the next.

**Comment by Sharonbc01** [comment]
@mandrigin can you advise if this issue is a requirement for mainnet milestone
