### ISSUE TITLE
[zero zkEVM] - remove unnecessary smt logic

### ISSUE THREAD

**Issue by krlosMata** [0xPolygon/cdk-erigon#1191]
# Rationale
Some storage slots in hermez SMT are specific to the hermez protocol. Therefore, some of them could be removed since zero protocol differs on how some variables are computed/loaded from the circuit perspective 
This issue aims to summarize all storage slots that are not needed for Zero prover: 
> [ADDRESS_SYSTEM address](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/constants.zkasm#L3) 
- **ADDRESS_SYSTEM:** [BlockInfoTreeRoot](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/constants.zkasm#L22)
  - `blockInfoTree` is no longer needed
  - zero uses native blockhash validation (same as Ethereum)
  - No need to write in this storage slot
- **ADDRESS_SYSTEM:** [mapping stateRoot](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/constants.zkasm#L20)
  - mapping to store all state-roots which are the blockjhahes for each block in a mapping like `mapping(uint256 blockNum => bytes32) blockToBlockHash;`
  - zero gets previous 256 blockhahes from an input which a commitment to the previous 256 blockhashes
  - no need to store them
- **ADDRESS_SYSTEM:** [lastBlock](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/constants.zkasm#L19)
  - hermez protocol ensures contiguity on block numbers through this storage slot in the state-tree
  - zero ensures contiguity via the parentHash
  - no need to write this storage slot
- **ADDRESS_SYSTEM:** [timestamp](https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/constants.zkasm#L21)
  - same as before, but this time related to the timestamp

**Comment by rachit77** [comment]
This [PR](https://github.com/0xPolygonHermez/cdk-erigon/pull/1374) which is merged fixes this issue.

**Comment by Stefan-Ethernal** [comment]
Marking as done per https://github.com/0xPolygonHermez/cdk-erigon/issues/1191#issuecomment-2477261504.
