### ISSUE TITLE
Method Handler Crash causing JSON RPC Issue

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#1197]
I'm doing a call to `debug_traceTransaction` and it's failing with `method handler crashed`. That's probably a different issue, but it looks like cast doesn't like that the response includes both `error` and `result`

![image](https://github.com/user-attachments/assets/b2c2ccf4-8fd7-4459-b9ab-ad1d264d5599)

From the [spec](https://www.jsonrpc.org/specification#response_object) it does seem like this shouldn't happen.
> Either the result member or error member MUST be included, but both members MUST NOT be included.

This is occurring with the one of the latest test images from @cffls `jerrycgh/cdk-erigon:8b4732a73f23a27990320f014bbad64b67d70bb7`

**Comment by V-Staykov** [comment]
Is the transaction on any network we can try querying as well, or do you have the transaction so we can reproduce it?

**Comment by cffls** [comment]
This should be fixed by https://github.com/0xPolygonHermez/cdk-erigon/pull/1201
