### ISSUE TITLE
[RPC/Sequencer] "the bug" implementation needs turning off for fork 12+

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#1235]
We found a very subtle bug in a fork 12 network where the RPC handles logs in receipts differently to the sequencer.  The code in question is in the `ApplyPaddingToLogsData` function on the `Log` type.

Initial thoughts are that we simply need to skip this behaviour completely if the fork 12+ is active, but we need to ensure this is safe to do for existing networks that upgrade to fork 12.

The sequencer also runs this code but only in L1 recovery, I think this also needs removing as it wasn't done on the first pass when building the chain in the first place.

**Comment by revitteth** [comment]
I think the behaviour to turn it off at 12+ is correct, going back to the original issue - it was the intention to remove the issue completely from 12, and we retain the code to handle for lower forkIds.

**Comment by hexoscott** [comment]
Perfect then

**Comment by Sharonbc01** [comment]
Hi @hexoscott was this item addressed where by the behaviour is turned off at 12+? Is this a configuration change @zuiris need to be aware of for Ares+ release that uses Fork 12 or is it a code change Gateway FM need to make? 

cc: @mandrigin

**Comment by hexoscott** [comment]
This one will require a code change and verifying against an old datastream we have that highlighted the issue to us.  All being well I'll get this done today/tomorrow.
