### ISSUE TITLE
[RPC] Failed to WriteTransactions: bucket: BlockTransaction On X Layer Testnet

### ISSUE THREAD

**Issue by zjg555543** [0xPolygon/cdk-erigon#1239]
#### System information

Erigon version:  v2.0.0-beta18.4

OS & Version:OSX

Commit hash: [f5bba0f](https://github.com/0xPolygonHermez/cdk-erigon/commit/f5bba0fdfd6dfcf375f72e4e51221136aaec911b)

Erigon Command (with flags/config):

./cdk-erigon-rpc --config="xlayerconfig-testnet.yaml"

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: X Layer Testnet

#### Expected behaviour
Synchronize the latest block from 0 should be successed.

#### Actual behaviour
Got error: failed to WriteTransactions: bucket: BlockTransaction, mdbx_cursor_put: MDBX_EKEYMISMATCH: The given key value is mismatched to the current cursor position

[1.log](https://github.com/user-attachments/files/17160008/1.log)

**Comment by V-Staykov** [comment]
This issue has been fixed but is not included in beta18.4

**Comment by zjg555543** [comment]
Cool
