### ISSUE TITLE
Enhance clarity of zkevm configuration flags

### ISSUE THREAD

**Issue by leovct** [0xPolygon/cdk-erigon#1253]
CDK-Erigon uses several configuration flags to specify addresses for crucial smart contracts in the zkevm ecosystem. The current naming convention may lead to confusion among developers, especially those new to the project. This proposal aims to improve clarity and consistency in our configuration.

| Current Flag | Proposed Flag | Description |
|--------------|---------------|-------------|
| `zkevm.address-rollup` | `zkevm.address-rollup-manager` | Address of the PolygonRollupManager contract |
| `zkevm.address-zkevm` | `zkevm.address-rollup` | Address of the specific Rollup contract |
| `zkevm.l1-rollup-id` | `zkevm.rollup-id` | Rollup identifier |

**Comment by revitteth** [comment]
Replacing with #1259
