### ISSUE TITLE
[zero zkEVM] - Remove post-state execution bits

### ISSUE THREAD

**Issue by Nashtare** [0xPolygon/cdk-erigon#1255]
This piece of execution below is not needed for zero zkEVM in the way it handles block hashes consistency, and would need to be removed to match the expected prover state:

https://github.com/0xPolygonHermez/cdk-erigon/blob/55ed01089b6ee5e34a298b7c6a20919ce41cacc3/core/blockchain_zkevm.go#L158-L176

**Comment by rachit77** [comment]
This [PR](https://github.com/0xPolygonHermez/cdk-erigon/pull/1374) which is already merged fixes this issue.
