### ISSUE TITLE
[Sequencer] reject transactions with gas higher than the cap

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#1265]
We need to add code to reject a tx as it is checked on entry to the pool that rejects transactions with >= 30m gas.  These transactions will never get executed so can be rejected immediately.

**Comment by afa7789** [comment]
this was fixed already by @V-Staykov , just not in the version this guys are using.

already debugged a bit more, considering it closed.

basically there was a >= instead of > in place to reject and it was not returning any errors there too.
