### ISSUE TITLE
Wrong `globalExitRoot` and `accInputHash` shown on PolygonScan (Cardona)

### ISSUE THREAD

**Issue by leovct** [0xPolygon/cdk-erigon#1289]
## Description

PolygonScan sometimes reports incorrect values for `globalExitRoot` and `accInputHash`.

An example of this can be seen with batch `128117` on Cardona, where the reported value does not align with our RPCs.

<img width="880" alt="polygonscan-wrong-global-exit-root" src="https://github.com/user-attachments/assets/870f18f3-6694-4d5f-954d-f91f2baa2796">

**Comment by V-Staykov** [comment]
What method does that script use to get the GER? Maybe some of our RPC methods returns a wrong value.

**Comment by leovct** [comment]
> What method does that script use to get the GER? Maybe some of our RPC methods returns a wrong value.

- fetch rpc data: https://gist.github.com/leovct/ea75e040b07375430fbb7ee195bceef7
- fetch polygonscan data: https://gist.github.com/leovct/b986d40cdeacbf782ea3a73db442bf21

**Comment by V-Staykov** [comment]
We have no access to how polygonscan gets that GER. Our endpoints seem to return the correct one, so it is strange that Polygonscan gets a different one. But the problem seems to be not on our side, if I am not missing something.

**Comment by Sharonbc01** [comment]
Hi @leovct  please can you reach out to Parvez Shaikh in Polygon who works with the Polygonscan team. If you can share some examples with him. I have given Parvez a heads ups and he is expecting to hear from you.

cc: @praetoriansentry

**Comment by leovct** [comment]
The Polygonscan team is currently synchronizing another Cardona node with version [v2.1.0](https://github.com/0xPolygonHermez/cdk-erigon/releases/tag/v2.1.0), which should correct the `accInputHash` and `globalExitRoot` mismatch. I'll close the issue for now. We'll run the same tests once their infra is updated.
