### ISSUE TITLE
Flexible Chain Initialization Handling

### ISSUE THREAD

**Issue by cffls** [0xPolygon/cdk-erigon#1300]
## Context
Today, a batch, called "initial batch", of transactions is sequenced in L1 before an L2 is created. The batch contains transactions such as bridge initialization. For rollups and validiums, the initial batch is read from L1 endpoint and written to the database in [`HandleInitialSequenceBatches`](https://github.com/0xPolygonHermez/cdk-erigon/blob/fe753f28b291f0d2e1e2221e4ac8e061d70f87ff/zk/stages/stage_l1_sequencer_sync.go#L248-L286), and [injected](https://github.com/0xPolygonHermez/cdk-erigon/blob/fe753f28b291f0d2e1e2221e4ac8e061d70f87ff/zk/stages/stage_sequence_execute_injected_batch.go#L25-L84) in execution stage. 

## New feature
In some scenarios, e.g. sovereign chains, the initialization transaction are not posted to L1. Instead, they could be written to a file or directly baked in the genesis. `cdk-erigon` should be able to handle both cases. 

#### Batch injection
The transactions should be read from a local file specified in configuration, and executed in execution stage. This logic could be added to [`processInjectedInitialBatch`](https://github.com/0xPolygonHermez/cdk-erigon/blob/fe753f28b291f0d2e1e2221e4ac8e061d70f87ff/zk/stages/stage_sequence_execute_injected_batch.go#L25-L84).
Notice that we can allow the file to be empty. When the file is provided but empty, it implies the initialization txns are already baked in genesis, and the same code logic will be able to handle both cases automatically.

#### Forkid 
Forkid is used in many places in cdk-erigon and it is initialized in injected batch. For some chains, forkid isn't even required. However, without picking a forkid, cdk-erigon might freeze or break at some stage (we should fix this in the end). For now, a quick work around is to pick the latest forkid and [write it to db](https://github.com/0xPolygonHermez/cdk-erigon/blob/fe753f28b291f0d2e1e2221e4ac8e061d70f87ff/zk/hermez_db/db.go#L1048-L1050) when forkid isn't required, e.g. sovereign chains.

**Comment by krlosMata** [comment]
> Forkid is used in many places in cdk-erigon and it is initialized in injected batch

ForkID is not set at the injected batch but when the [rollup is created](https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/contracts/v2/PolygonRollupManager.sol#L239).
You can derive its `rollupTypeID` and from the `rollupTypeID` you can [check the forkID](https://github.com/0xPolygonHermez/zkevm-contracts/blob/main/contracts/v2/PolygonRollupManager.sol#L173) 

In sovereignChains, forkID acts in the SC side as a metadata.
