### ISSUE TITLE
[Sequencer] log messages when overflowing counters are causing confusion.

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#1309]
The logs messages when we attempt to add a transaction to a batch and it overflows counters are confusing as it looks like a single transaction is overflowing the counters and that it is somehow invalid.  We need to soften the message below to make it clearer that we're simply trying to maximise the batch capacity and the tx will be attempted in the next batch.

```
log.Info(fmt.Sprintf("[%s] transaction %s overflow counters", logPrefix, txHash), "count", batchState.overflowTransactions)
```

**Comment by hexoscott** [comment]
We should also log the current state of the steps in this message to show what is going on, maybe just the ones that overflowed and by how much.  So make it clear that this single transaction took the batch from 10k steps to 50k steps so we'll try in the next batch.

**Comment by afa7789** [comment]
Looking into it.
