### ISSUE TITLE
Typo in log message: "EROR" should be "ERROR"

### ISSUE THREAD

**Issue by leovct** [0xPolygon/cdk-erigon#1313]
## Description

This issue reports a typo in the log message where "ERROR" is incorrectly spelled as "EROR".

<img width="1049" alt="Screenshot 2024-10-14 at 16 11 33" src="https://github.com/user-attachments/assets/f95b12e2-012c-40f0-8cfa-75286e012646">

This is related to the [ledgerwatch/log](https://github.com/ledgerwatch/log) fork which returns "eror" instead of "error". 

Also we should also maybe return "debug" instead of "dbug".

```go
// Returns the name of a Lvl
func (l Lvl) String() string {
	switch l {
	case LvlTrace:
		return "trace"
	case LvlDebug:
		return "dbug"
	case LvlInfo:
		return "info"
	case LvlWarn:
		return "warn"
	case LvlError:
		return "eror"
	case LvlCrit:
		return "crit"
	default:
		panic("bad level")
	}
}
```

https://github.com/ledgerwatch/log/blob/c5a577bdb8ef76d97b744ebc8ff2d5d0b187501b/v3/logger.go#L40-L41

**Comment by leovct** [comment]
It looks related to this issue: https://github.com/inconshreveable/log15/pull/140

**Comment by revitteth** [comment]
This is incorrectly spelled in order to maintain the log layout.
