### ISSUE TITLE
[Sequencer] delays in interacting with executors

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#1319]
It looks like we have a bottleneck in networks with a small number of executors.  From the outside it appears that we only send a single request to an executor and don't trigger the next request until we have handled the response from the first one.  This means that without scaling to many executors to round-robin them that we can create a very large gap between the sequencer and RPC node. We're effectively only sending one executor request per block creating a bottleneck, even if the executor responds in 100ms we are waiting until the next block is built to check.

**Comment by Sharonbc01** [comment]
@zuiris can this be closed now that John has confirmed the fix https://0xpolygon.slack.com/archives/C06B9L32F8E/p1729010040241289
