### ISSUE TITLE
[Bug] In the CDK_ERIGON_SEQUENCER=0 mode, and make the cdk-erigon generate Datastream, the cdk-erigon will be  halted.

### ISSUE THREAD

**Issue by lyh169** [0xPolygon/cdk-erigon#1353]
Erigon version: ./cdk-erigon --version
v1.2.15.7

The config is :
CDK_ERIGON_SEQUENCER=0
```
zkevm.data-stream-host: "0.0.0.0"
zkevm.data-stream-port: 6990
zkevm.default-gas-price: 1000000000
zkevm.max-gas-price: 0
zkevm.gas-price-factor: 0.000001
```
I run the cdk-erigon,  the program will be halted, when after executed the `CatchupDatastream` and run the `tx.Commit()`. This happened in a large number(about 10000000) of block in generate the data stream. 
The functionj of `tx.Commit()`  halted about more than one day or more( because i just wait for that time)。 

```
func SpawnStageDataStreamCatchup(
	s *stagedsync.StageState,
	ctx context.Context,
	tx kv.RwTx,
	cfg DataStreamCatchupCfg,
) error {
	logPrefix := s.LogPrefix()
	log.Info(fmt.Sprintf("[%s] Starting...", logPrefix))
	stream := cfg.stream

	if stream == nil {
		// skip the stage if there is no streamer provided
		log.Info(fmt.Sprintf("[%s] no streamer provided, skipping stage", logPrefix))
		return nil
	}

	createdTx := false
	if tx == nil {
		log.Debug(fmt.Sprintf("[%s] data stream: no tx provided, creating a new one", logPrefix))
		var err error
		tx, err = cfg.db.BeginRw(ctx)
		if err != nil {
			return fmt.Errorf("failed to open tx, %w", err)
		}
		defer tx.Rollback()
		createdTx = true
	}

	finalBlockNumber, err := CatchupDatastream(ctx, logPrefix, tx, stream, cfg.chainId, cfg.streamVersion, cfg.hasExecutors)
	if err != nil {
		return err
	}

	if createdTx {
		log.Info("********: tx.Commit start")
		if err := tx.Commit(); err != nil {
			log.Error(fmt.Sprintf("[%s] error: %s", logPrefix, err))
		}
		log.Info("********: tx.Commit end")
	}

	log.Info(fmt.Sprintf("[%s] stage complete", logPrefix), "block", finalBlockNumber)

	return err
}
```

**Comment by afa7789** [comment]
@lyh169 what else you did to get to this issue ?

could you share more steps ?

who you are connecting to, etc ?

I ran a sequencer here, and connect a RPC client to it, to share a data stream from it and was not able to get to the halt.
If you share more details related to your build I think I will be able to reproduce it better. 

you are probably using an older version of cdk-erigon, have you tried updating it ?

**Comment by lyh169** [comment]
> @lyh169 what else you did to get to this issue ?
> 
> could you share more steps ?
> 
> who you are connecting to, etc ?
> 
> I ran a sequencer here, and connect a RPC client to it, to share a data stream from it and was not able to get to the halt. If you share more details related to your build I think I will be able to reproduce it better.
> 
> you are probably using an older version of cdk-erigon, have you tried updating it ?

Yes, thanks, the new version of cdk-erigon(v1.2.26)  have fixed this bug.

**Comment by afa7789** [comment]
@lyh169  I'm glad it's fixed, but that's not the latest version:
https://github.com/0xPolygonHermez/cdk-erigon/releases

check this later.
