### ISSUE TITLE
High CPU Utilization from RPC Node from DatastreamClientRunner

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#1387]
After upgrading to zkevm branch, the RPC node needs to constantly use a lot of CPU. The pprof CPU looks like this:

![image](https://github.com/user-attachments/assets/1146eb6a-ce1e-421f-8bdc-b35bc66adaa4)

I'm seeing this performance on this commit: 434376b78c60ff5cfdf1c6efebe813690f8d73d5

**Comment by cffls** [comment]
Potential fix: https://github.com/0xPolygonHermez/cdk-erigon/pull/1389

**Comment by V-Staykov** [comment]
This should be fixed by this older PR:https://github.com/0xPolygonHermez/cdk-erigon/pull/1297

And #1389 will be conflicting with it. 

Can we merge only the test in a separate PR, so we can check if it passes with the first PR merged?

**Comment by cffls** [comment]
Nice, thanks @V-Staykov ! I will keep only the test in #1389.

**Comment by Sharonbc01** [comment]
**Update.** 
Fix to high CPU problem has been merged: https://github.com/0xPolygonHermez/cdk-erigon/pull/1297

**Comment by Sharonbc01** [comment]
John confirmed good
