### ISSUE TITLE
Verions of cdk-erigon < 2.60 will not reconize `AddNewRollupType`

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#1422]
There are two different event signatures for `AddNewRollupType` now

| Signature | Selector |
|---|---|
| AddNewRollupType(uint32,address,address,uint64,uint8,bytes32,string,bytes32)                    | 0x9eaf2ecbddb14889c9e141a63175c55ac25e0cd7cdea312cdfbd0397976b383a |
| AddNewRollupType(uint32,address,address,uint64,uint8,bytes32,string)                              | 0xa2970448b3bd66ba7e524e7b2a5b9cf94fa29e32488fb942afdfe70dd4b77b52 |

These are both supported in the latest versions of cdk-erigon:
https://github.com/0xPolygonHermez/cdk-erigon/blob/6e8775f714f848780f0782b9a0538aad23c7d73e/zk/contracts/l1_contracts.go#L16-L17

The challenge is, once we update the rollup manager contract, that means older versions of cdk-erigon / cdk-validium-node might have issues being attached or doing an L1 recovery.

**Comment by Sharonbc01** [comment]
Hi @mandrigin I wanted to make you aware of this issue that John found when testing with the new PP Smart contracts. This is important to consider with your presto team WRT setting up new chains. I see on the presto roadmap our next chain is the WW to be set up to use PP which we should use CDK Erigon v2.60.x  for anyway.

cc: @krlosMata

**Comment by mandrigin** [comment]
yeah, so let's close this issue, since it is more like JFYI
