### ISSUE TITLE
[Sequencer] txpool to remove old transactions

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#1459]
In certain networks the number of transactions grows quite quickly and old transactions can sit consuming space.

The task is to have a new flag `zkevm.txpool-tx-age` which is set to a timeframe (defaulted to 24h).  When a new transaction comes in we mark the time on it and a cleanup process runs every minute to check for and remove old transactions.  When the pool does this it should log at debug level the hash which was removed and ideally for which account as well.

**Comment by mandrigin** [comment]
fixed by https://github.com/0xPolygonHermez/cdk-erigon/pull/1471
