### ISSUE TITLE
Unable to retrieve nonce at current height

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#1460]
It seems like implementations for fetching the nonce at the current block height don't work. `latest` seems to be fine.

Making this call 
```
cast nonce --block $(cast block-number --rpc-url https://rpc.internal.zkevm-rpc.com) --rpc-url https://rpc.internal.zkevm-rpc.com 0xCE27d8BCee45dB3E457EcF8629264Ca7893AAaAc
```

will fail with an error like:
```
server returned an error response: error code -32000: RPC error response: block with number 7527390 not found
```

But such a call will work fine against mainnet:
```
cast nonce --block $(cast block-number --rpc-url https://zkevm-rpc.com) --rpc-url https://zkevm-rpc.com 0xCE27d8BCee45dB3E457EcF8629264Ca7893AAaAc
```

**Comment by revitteth** [comment]
Fixed by: https://github.com/0xPolygonHermez/cdk-erigon/pull/1473

**Comment by Sharonbc01** [comment]
Hey @revitteth we still need to validate this issue when merged into beta 10 so any objection to me leaving this open?

cc: @praetoriansentry

**Comment by revitteth** [comment]
Yeah good plan!

**Comment by praetoriansentry** [comment]
This looks good to me now.

**Comment by Sharonbc01** [comment]
Thanks John will close
