### ISSUE TITLE
Refactor `SpawnStageBatches` function

### ISSUE THREAD

**Issue by Stefan-Ethernal** [0xPolygon/cdk-erigon#1476]
The `SpawnStageBatches` is large ([cdk-erigon/zk/stages/stage_batches.go at 1c66851ea12ffde9bf2c1ba0fc4c54d293635157 · 0xPolygonHermez/cdk-erigon](https://github.com/0xPolygonHermez/cdk-erigon/blob/1c66851ea12ffde9bf2c1ba0fc4c54d293635157/zk/stages/stage_batches.go#L133-L573) ), which makes it hard to understand and maintain. Consider refactoring it into smaller, manageable, and easier-to-understand and maintain functions.

**Comment by V-Staykov** [comment]
This is already refactored and a lot shorter with the latest changes: 
https://github.com/0xPolygonHermez/cdk-erigon/blob/zkevm/zk/stages/stage_batches.go

**Comment by hexoscott** [comment]
Closing based on the recent refactor.
