### ISSUE TITLE
modexp test causes state root missmatch (fork13)

### ISSUE THREAD

**Issue by xavier-romero** [0xPolygon/cdk-erigon#1484]
[This test vector](https://github.com/0xPolygonHermez/zkevm-testvectors/blob/2b70027e11a427c15994713b41ef9b6794c2f3bb/tools-inputs/data/calldata/pre-modexp.json#L787
) from @laisolizq causes a state root missmatch:

Run from [this test script](https://github.com/xavier-romero/eth-bench/blob/main/scripted/modexp-laia-issue-3.1.json).

You can easily reproduce it that way:
```
RPC_URL=http://x.x.x.x:8123
PRIVKEY=0000000000000000000000000000000000000000000000000000000000000000

docker pull xavierromero/devtooling

docker run --name devtooling --rm \
    -e L2_RPC_URL=$RPC_URL \
    -e L2_PRV_KEY=$PRIVKEY \
    xavierromero/devtooling \
    scripted -f /scripted/modexp-laia-issue-3.1.json

```

**Comment by Sharonbc01** [comment]
@hexoscott please highlight when this fix in release and in what release for testing.

**Comment by Sharonbc01** [comment]
once Gateway FM cut stable/2.61 this fix will go into images targeting fork 13

**Comment by hexoscott** [comment]
The latest code for this is now merged including updated unit tests, we haven't cut 2.61 yet but should we close this issue down as zkevm branch is effectively ready to test fork13 from now?

**Comment by laisolizq** [comment]
https://github.com/0xPolygonHermez/cdk-erigon/pull/1494
