### ISSUE TITLE
Datastream warnings: expecting result packet type 255 and received 2

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#1491]
I'm running `v2.60.0-beta10` against bali, cardona, zkevm-mainnet, and xlayer-mainnet and I see occasional warnings in all three networks:
![image](https://github.com/user-attachments/assets/0aed5ec9-d3df-435c-9e10-78d961e937f4)

```
getLatestL2Block: GetHeader: expecting result packet type 255 and received 2
getLatestL2Block: NextFileEntry: expected data packet type 2 or 254 and received 1
```

I can't see any side effect or impact at the moment.

**Comment by hexoscott** [comment]
Related to #1485 - you start to receive these messages after a network blip

**Comment by Sharonbc01** [comment]
Confirmed fixed with RC4
