### ISSUE TITLE
`v2.60.0` complains that MDBX DB is too large

### ISSUE THREAD

**Issue by yorickdowne** [0xPolygon/cdk-erigon#1511]
Tested on Polygon-zkEVM mainnet and XLayer mainnet. DBs are 160GB and 51GB respectively.

On startup:
```
cdk-erigon-1  | [INFO] [11-28|08:05:34.916] Opening Database                         label=chaindata path=/home/erigon/.local/share/erigon/chaindata
cdk-erigon-1  | mdbx_setup_dxb:15897 could not apply preconfigured db-geometry: err -30417
cdk-erigon-1  | [EROR] [11-28|08:05:34.918] Erigon startup                           err="mdbx_env_open: MDBX_TOO_LARGE: Database is too large for current system, e.g. could NOT be mapped into RAM, label: chaindata, trace: [kv_mdbx.go:358 node.go:367 node.go:370 backend.go:270 node.go:131 main.go:73 make_app_zkevm.go:46 command.go:276 app.go:333 app.go:307 main.go:46 proc.go:267 asm_amd64.s:1650]"
cdk-erigon-1  | mdbx_env_open: MDBX_TOO_LARGE: Database is too large for current system, e.g. could NOT be mapped into RAM, label: chaindata, trace: [kv_mdbx.go:358 node.go:367 node.go:370 backend.go:270 node.go:131 main.go:73 make_app_zkevm.go:46 command.go:276 app.go:333 app.go:307 main.go:46 proc.go:267 asm_amd64.s:1650]
```

The same DB on `v2.0.1` works well.

We added `--db.size.limit 1TB` and the error resolved. With that, `v2.60.0` starts successfully.

pageSize is left at default, `4096`

Desired change: `v2.60.0` has a high enough DB size limit baked in to run Polygon-zkEVM and XLayer out of the box.

**Comment by V-Staykov** [comment]
What system are you running this? The default value of ``db.size.limit` is 12TB.

**Comment by V-Staykov** [comment]
The default value of the flag is 12TB. What hardware are you running this on?

**Comment by yorickdowne** [comment]
Maybe it’s a behavior caused by having an older DB? A fellow NO saw the same thing.

We run on 8 cores / 16 threads, 128 GiB RAM, 7 TiB NVMe.

**Comment by hexoscott** [comment]
`db.size.limit: 8TB` should be the silver bullet.  As for older DBs, version 2.60.X is incompatible with a DB created by a 2.0.X version so will require a full re-sync on the newer version.
