### ISSUE TITLE
[Sequencer] "INTERNAL_ERROR: could not replace existing tx" Error When Sending Transaction

### ISSUE THREAD

**Issue by zjg555543** [0xPolygon/cdk-erigon#1514]
**Versions：**
- Private network
- Erigon: [xlayer dev](https://github.com/okx/xlayer-erigon/tree/dev) which base on [v2.60.0](https://github.com/0xPolygonHermez/cdk-erigon/releases/tag/v2.60.0)
- Contract: ForkID.13

**Reproduction**
- Stress txs for a period of time, RPC node can't sync with Seq node.

I'm encountering an issue when trying to send a transaction using Erigon where I receive the following error:` INTERNAL_ERROR: could not replace existing tx`. This happens when attempting to send a new transaction with the same nonce as an existing one.

**Steps to Reproduce:**

1. Send a transaction using the following command (details are obfuscated for privacy):
`cast send -f 0x2206812B69662f454C5218E4BaC20E439e15c4c5 --private-key 0xxxxxxxx --value 0.01ether 0xA6f7A6b2E9B4d41C582D4Aaf907F45321e2Ca847 --legacy --rpc-url http://erigon-rpc.vali-global.svc.test.local:8545`
2.  The command returns the following error:
`Error: server returned an error response: error code -32000: RPC error response: INTERNAL_ERROR: could not replace existing tx`

**Expected Behavior:**

The new transaction with the same nonce should either replace the existing transaction if it has a higher gas price or be accepted if the previous one is not in the pool anymore.

**Actual Behavior:**

The transaction is rejected with the error code `-32000: INTERNAL_ERROR: could not replace existing tx`, indicating that the transaction cannot be replaced.

Environment:

RPC URL: http://erigon-rpc.vali-global.svc.test.local:8545

Cast version: cast 0.2.0 (995fd9e 2024-11-26T00:22:03.572961224Z)

OS: Alibaba Cloud Linux 3 (Soaring Falcon), VERSION_ID=3, UPDATE_ID=9.1

Additional Information:

I have tried the following to resolve the issue:

Used the `cast nonce` command to verify the correct nonce for the address, which confirmed the correct nonce.

Increased the gas price to a higher value to incentivize miners, but the issue persisted.

Attempted to replace the transaction with a 0 value transaction to cancel it, but still faced the same error.

Any guidance or insights into why the transaction cannot be replaced would be greatly appreciated. Is there any specific configuration or limitation in Erigon that could be causing this behavior?

**Comment by zjg555543** [comment]
The pool has pending txs, but seq didn't pack there txs. Here is the `txpool_content` response and sequencer logs.
[pool.json](https://github.com/user-attachments/files/17946257/pool.json)
[seq.log](https://github.com/user-attachments/files/17946273/seq.log)

**Comment by hexoscott** [comment]
If you would like any price increase to replace an existing transaction you can set `txpool.pricebump: 0` in your config.  This figure sets a percentage increase needed to replace a transaction, setting it to 0 will mean any increase will replace it.
