### ISSUE TITLE
v2.60.0 Failed to get AccInputHash

### ISSUE THREAD

**Issue by vlady-kotsev** [0xPolygon/cdk-erigon#1517]
`2024-11-28 15:29:27 [EROR] [11-28|13:29:27.631] failed to get acc input hash for batch 14: failed to get current batch sequence for batch 14 
2024-11-28 15:29:27 [EROR] [11-28|13:29:27.634] failed to get acc input hash for batch 15: failed to get current batch sequence for batch 15 `

I'm running the latest kurtosis-cdk. Due to this error accInputHash remains 0x000... This needs to be fixed in order to run a real prover and then verify the proof. The accInputHash is used as a public input for the verifier.

**Comment by Sharonbc01** [comment]
Hi @mandrigin any update on this please?

**Comment by Sharonbc01** [comment]
Moving this from current milestone as Igor noted its not required for this milestone at this time.

**Comment by V-Staykov** [comment]
This still seems to be an issue for Vlady.

**Comment by jhkimqd** [comment]
This was because of using an older image of the cdk-node within Kurtosis CDK. After using the latest image, the user can generate the accInputHash without issue! 
cc @vlady-kotsev
