### ISSUE TITLE
[Sequncer] v2.60.0 returns outdated latest block until the batch is closed.

### ISSUE THREAD

**Issue by iszubok** [0xPolygon/cdk-erigon#1520]
We have batch sealing time set to 30 minutes.
When launching a new network from genesis, the sequencer node returns block #1 as a response to `{ "id": 1, "jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["latest", false] }` despite new blocks are produced by the sequencer (can be seen from sequencer logs). Looks like the seuqencer always returns the latest block in the latest closed batch and not the latest block in WIP batch.

Request to fix this to support small single node devnet setups without runing a separate RPC node.

**Comment by afa7789** [comment]
@iszubok, could you share config/reproduction steps?

**Comment by hexoscott** [comment]
Fixed by #1527
