### ISSUE TITLE
ZkEvm Is not starting

### ISSUE THREAD

**Issue by Damantino** [0xPolygon/cdk-erigon#157]
#### System information

- 22.04.1-Ubuntu LTS
- cdk-erigon version 2.43.0-dev-e8383ace
- Branch zkevm
- Tag v0.0.2-alpha

Config file:

```yaml
datadir : '/mnt/ethereum/cdk-erigon-data/hermez-mainnet/'
chain : "hermez-mainnet"
http : true
private.api.addr : "localhost:9091"
zkevm.l2-chain-id: 1101
zkevm.l2-sequencer-rpc-url: "https://zkevm-rpc.com"
zkevm.l2-datastreamer-url: "stream.zkevm-rpc.com:6900"
zkevm.l1-chain-id: 1
zkevm.l1-rpc-url: "http://localhost:8545/"
zkevm.l1-contract-address: "0x5132A183E9F3CB7C848b0AAC5Ae0c4f0491B7aB2"
zkevm.l1-block-range: 20000
zkevm.l1-query-delay: 6000
zkevm.l1-matic-contract-address: "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0"
zkevm.l1-ger-manager-contract-address: "0x580bda1e7A0CFAe92Fa7F6c20A3794F169CE3CFb"
zkevm.l1-first-block: 16896700
zkevm.rpc-ratelimit: 250

externalcl: true
http.api : ["eth","debug","net","trace","web3","erigon","zkevm"]
```

Erigon Command:

- `./build/bin/cdk-erigon --torrent.port=42070 --config="/mnt/ethereum/cdk-erigon/hermezconfig-mainnet.yaml"`

#### Expected behaviour

Starts and synchronizes

#### Actual behaviour

Stays at infinite loop:

```bash
INFO[02-22|20:40:48.425] [2/15 Batches] Starting batches stage
INFO[02-22|20:40:48.426] [2/15 Batches] Starting stream           startBlock=0
INFO[02-22|20:40:48.426] [2/15 Batches] Reading blocks from the datastream.
INFO[02-22|20:40:48.426] [2/15 Batches] Started downloading L2Blocks routine
INFO[02-22|20:40:48.426] [2/15 Batches] Finished downloading L2Blocks routine
INFO[02-22|20:40:48.426] [2/15 Batches] Finished Batches stage
EROR[02-22|20:40:48.426] Staged Sync                              err="[2/15 Batches] l2blocks download routine error: bad bookmark"
```

Note that I've tried [this](https://github.com/0xPolygonHermez/cdk-erigon/issues/46) solution but keeps failing for me.

Any help would be appreciated.

**Comment by V-Staykov** [comment]
Your config file seems old. We've put out some updates that are not in the release. Please get the latest commit from zkEvm branch and copy all but the datadir value and try again. 

Also are there any warnings or errors prior to this since the start? The whole log might be useful.

**Comment by Damantino** [comment]
So I have to work on zkevm and git pulling anytime you guys make an update?

Shouldn't it work with the latest tag?

**Comment by V-Staykov** [comment]
It is still alpha and we are making a lot of changes everyday. We just haven't made a release in a few weeks. We will make one today or tomorrow.

**Comment by Damantino** [comment]
Okay, seems to work with latest changes, will try again when the latest tag is made

**Comment by V-Staykov** [comment]
We've made a release v0.0.3-alpha. I am closing this issue.
