### ISSUE TITLE
Unable to recover from L1 for Cardona testnet

### ISSUE THREAD

**Issue by cffls** [0xPolygon/cdk-erigon#1573]
When recovering from L1, the node ran into an issue where it wasn't able to detect the forkid for Cardona:

```
[WARN] [12-12|13:55:46.022] [5/13 Execution] ForkId is 0. Waiting for L1 to finalise a block... 
```

Node version is `v2.60.0`

**Comment by V-Staykov** [comment]
Was the recovery started from zero? If yes, that is expected.

**Comment by cffls** [comment]
Yes, it was recovered from genesis.

**Comment by V-Staykov** [comment]
So networks that start pre forkId8 are not recoverable by l1. One way to do it is to sync like an RPC with a limit up to a forkid8 batch end and then switch to a sequencer with recovery. I've added this to the docs in the PR above.
