### ISSUE TITLE
Unable to recover from L1 after unwinding

### ISSUE THREAD

**Issue by cffls** [0xPolygon/cdk-erigon#1574]
After a sequencer is unwound to a previous block, we are not able to recover it from L1, and it will get stuck in a loop "The node need re-sequencing but this option is disabled" (see attached screenshot). 

I think the problem is that the datastream is ahead of db after unwinding, and when the node restarts, it will try to re-sequence after observing the difference of block tip between the ds and db. 

![image](https://github.com/user-attachments/assets/aca6850f-746f-474a-9c50-6762d9febdba)

**Comment by revitteth** [comment]
I guess on the unwind we should truncate/remove the local DS?

**Comment by V-Staykov** [comment]
@cffls was the sequencer unwound manually and how, or it unwound itself for some reason?
