### ISSUE TITLE
[Sequencer] network upgrade transactions

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#274]
We currently don't handle the network upgrade transactions to change between forks, we need to look at how to process these properly.

**Comment by Sharonbc01** [comment]
Hi @hexoscott do you agree this issue can be closed as I have issues https://github.com/0xPolygonHermez/cdk-erigon/issues/1030 & https://github.com/0xPolygonHermez/cdk-erigon/issues/1038 for Polygon to perform the fork upgrade?

**Comment by hexoscott** [comment]
Hi @Sharonbc01 - I'd agree this can be closed now.  We had the code in place for the Bali fork upgrade when it switched to CDK-erigon.
