### ISSUE TITLE
Dynamic Fork Enablement

### ISSUE THREAD

**Issue by revitteth** [0xPolygon/cdk-erigon#37]
The datastream contains fork_id messages which allow the detection of hardfork enablement in the Hermez network. These are stored into MDBX.

Use the fork ids from the stream to enable Erigon hard forks.

**Comment by zjg555543** [comment]
name | ID | Add precomiled | Instruction changed | remark
-- | -- | -- | -- | --
? | forkID4 | ecRecover<br>identity   | CALLDATALOAD<br>CALLDATACOPY<br>STATICCALL<br>NUMBER<br>DIFFICULTY<br>BLOCKHASH<br>EXTCODEHASH<br>SENDALL |  Maybe added by the pre fork
dragonfruit<br>(mordor) | forkID5 | no changed | PUSH0<br>CALLDATACOPY<br>CALLDATALOAD<br>STATICCALL | [upgrade doc](https://polygon.technology/blog/polygon-zkevm-inca-berry-upgrade-coming-to-mainnet-beta)
Inca Berry | forkID6 | no changed | FflonkVerifier.sol | [upgrade doc](https://polygon.technology/blog/polygon-zkevm-dragon-fruit-upgrade-with-new-opcode-coming-to-mainnet-beta)
etrog | forkID7 | sha26<br>modexp<br>ecAdd<br>ecMul<br>ecPairing |   |

**Comment by zjg555543** [comment]
Here is the https://github.com/0xPolygonHermez/cdk-erigon/pull/52.
It had been test successd on hermez mainnet and x1 testnet, and waiting for https://github.com/0xPolygonHermez/cdk-erigon/pull/48 be done.

**Comment by revitteth** [comment]
Manual rebase (authored as @zjg555543) and pushed on another PR: https://github.com/0xPolygonHermez/cdk-erigon/pull/85 since a lot of files were moved between this PR and the zkevm.
