### ISSUE TITLE
[RPC] Create a special mode to send batches to the stateless executor for RPC

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#389]
We need to test the stateless executor for all possible edge cases, the idea is to call it for each processed batch when syncing RPC. We want to replay batches for Cardona and Mainnet.

Important limitation is that only supported forkid is starting from `forkid.7`, so everything older than that should be ignored.

In case of an error (mismatch of root hashes, missing key) -- panic!

**Comment by revitteth** [comment]
Superceded by l1 verification mode.
