### ISSUE TITLE
[Sequencer] conduct testing and fix issues with stateless-executor and Cardona batches

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#396]
use #389 to run this over Cardona and the latest stateless-executor to find edge cases and crashes there

**NB!** very important to verify our virtual counters against the actual counters from the stateless-executor!

**Comment by mandrigin** [comment]
First wave of testing is done. Fixing issues. 14% failure rate.

**Comment by mandrigin** [comment]
We conducted a test to connect an external executor to Erigon and re-ran all Cardona batches. Following the latest fixes, only transient issues remain, and we can’t reproduce the failures. Currently, the failure rate is about 0.2%.

We are updating our methodology:

* Now, we will run at least two independent tests.
* We will store the data sent to the executor in files.
* This approach allows us to verify whether we are sending incorrect data or if the instability is on the executor side.

**Comment by Sharonbc01** [comment]
@mandrigin can this be closed now?

**Comment by mandrigin** [comment]
no issues anymore, closing
