### ISSUE TITLE
[Sequencer] use rpc with stateless-executor to re-run zkEVM Mainnet batches

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#397]
use #389 to run RPC with a stateless executor and re-verify mainnet batches there

**NB!** very important to verify our virtual counters against the actual counters from the stateless-executor!

**Comment by Sharonbc01** [comment]
@revitteth as https://github.com/0xPolygonHermez/cdk-erigon/issues/389 is merged. Has this test been done?

**Comment by Sharonbc01** [comment]
Hi @revitteth please can you update on if this issue can be closed please?

**Comment by Sharonbc01** [comment]
Feedback from @mandrigin Given we have passed fuzzing tests and they are more comprehensive then these tests we can close this issue
