### ISSUE TITLE
[Sequencer] Support recovering from DAC for CDK (Validiums)

### ISSUE THREAD

**Issue by zjg555543** [0xPolygon/cdk-erigon#406]
# DAC Recovery Feature

## Overview

The DAC recovery feature enables the system to continue the blockchain using data from the Data Availability Committee (DAC). This is akin to the existing L1 recovery mode but utilizes data from the DAC instead of the L1.

## Implementation Steps

Add a separate mode, similarly to L1 recovery, that will read data from DAC instead of L1.

**Comment by mandrigin** [comment]
We support everything for validium apart from recovering from DAC. Will rename the issue and add to the right milestone.

**Comment by zjg555543** [comment]
@bylingo and me will follow this issue, we will write an design doc on next Tuesday.

**Comment by mandrigin** [comment]
I think the CDK people are looking at that.

**Comment by Sharonbc01** [comment]
Hi @zuiris assigning this task to you as Igor assumes this is work to be done by the Polygon CDK team. 
related Jira tickets https://polygon.atlassian.net/browse/CDK-234 and https://polygon.atlassian.net/browse/CDK-235

**Comment by zjg555543** [comment]
That's very great! @zuiris When do you plan to complete it? This is very important to us because xlayer is developed based on CDK.

**Comment by zjg555543** [comment]
Support validium funciton.
Hi @zuiris I have written some modification ideas, please help to review whether it is reasonable.

1.**zkevm-synchronizer-l1**: When syncing L1 batches, it needs to handle both validium and rollup batch data.
- [sequencedBatchesEvent](https://github.com/0xPolygonHermez/zkevm-synchronizer-l1/blob/develop/etherman/etherman.go#L1301)
- decodeSequencesEtrog
- decodeSequencesElderberry

2.**zkevm-sequence-sender**: Should the sequence sender support both rollup and validium modules simultaneously? (It seams great that Validium functionality already implemented)
- [BuildSequenceBatchesTxData](https://github.com/0xPolygonHermez/zkevm-sequence-sender/pull/30/files#diff-9420435b2f8e7ca901e1efd3c5f0dd6c7e267d8a90ae837c135fbd8f239ea5bfR469)

3.**erigon as sequencer**: As a Sequencer, it needs to recover and sync L1 sequencedBatch, so it needs to fetch specific content from DAC.
- [syncer.NewL1Syncer](https://github.com/0xPolygonHermez/cdk-erigon/blob/v1.0.10/eth/backend.go#L842)
- [DecodeL1BatchData](https://github.com/0xPolygonHermez/cdk-erigon/blob/v1.0.10/zk/stages/stage_sequencer_l1_block_sync.go#L154)

4.**erigon as rpc**:As an RPC node, it needs to sync L1 sequencedBatch and requires only the batch number, without relying on DAC for specific content.
- [syncer.NewL1Syncer](https://github.com/0xPolygonHermez/cdk-erigon/blob/v1.0.10/eth/backend.go#L787)
- [parseLogType](https://github.com/0xPolygonHermez/cdk-erigon/blob/v1.0.10/zk/stages/stage_l1syncer.go#L214)

**Comment by Sharonbc01** [comment]
Tagging @cffls who is working on this with the CDK team.

**Comment by cffls** [comment]
I am working on supporting validium mode (recovering from L1) in cdk-erigon. Will raise a PR once it is available. 
For 2,3, and 4, we have a [WIP PR](https://github.com/0xPolygon/kurtosis-cdk/pull/83) in kurtosis.

**Comment by mandrigin** [comment]
Great news!

**Comment by cffls** [comment]
PR for recovering in validium mode: https://github.com/0xPolygonHermez/cdk-erigon/pull/560

**Comment by mandrigin** [comment]
fixed by https://github.com/0xPolygonHermez/cdk-erigon/pull/560
