### ISSUE TITLE
[Sequencer] Reorg mechanism

### ISSUE THREAD

**Issue by zjg555543** [0xPolygon/cdk-erigon#408]
L1 maybe reorg blocks.

Q: Does stage_sequencer_l1_block_sync need to handle reorg?

**Comment by revitteth** [comment]
2 points here I think:

- l1 syncer - needs to use finalized block (PR incoming)
- the l1 block sync stage will be used in a context where the user would need to realise there is a reorg and should unwind/run it again

**Comment by revitteth** [comment]
https://github.com/0xPolygonHermez/cdk-erigon/pull/414 - fixes l1 syncer
