### ISSUE TITLE
[Sequencer] whitelist accounts send tx with 0 gas fee

### ISSUE THREAD

**Issue by zjg555543** [0xPolygon/cdk-erigon#409]
To specify whitelisted accounts for sending tx with 0 gas fee, such as claim bridge tx or oracle tx

Q: Is it implemented with the zkevm.allow-free-transactions flag?

**Comment by mandrigin** [comment]
No, this just allows 0 gas price transaction. Whitelist is to be implemented. I think the CDK team is on it right now.

**Comment by Sharonbc01** [comment]
Hi @zuiris is this the same as supporting allow lists that Rachit is working on?

**Comment by Sharonbc01** [comment]
Hi @zuiris assigning this task to you as Igor assumes this is work to be done by the Polygon CDK team.
related Jira tickets https://polygon.atlassian.net/browse/CDK-233
