### ISSUE TITLE
Consistency test for state

### ISSUE THREAD

**Issue by louisliu2048** [0xPolygon/cdk-erigon#43]
# Rationale

Make sure that all states in zkvm HashDB appear in erigon StateDB. 
Currently, we only compare rootHash, but that's not enough.

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by revitteth** [comment]
It would be good to provide some verification of tracing and other features making use of indices. With regards to implementation we'd welcome a PR if possible!
