### ISSUE TITLE
[Sequencer] Search for txs overflowing virtual counters on Cardon and Mainnet

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#434]
•	Utilize virtual counters for each transaction while syncing.
•	Reset counters after each transaction.
•	Verify that no transactions exceed counter limits on Cardona and ZKEVM mainnet networks.
•	Log each transaction that overflows counters, including its hash, block number, and counter values.

**Comment by V-Staykov** [comment]
[overflownTxs-Mainnet.json](https://github.com/user-attachments/files/15531078/overflownTxs-Mainnet.json)
[overflownTxs-Cardona.json](https://github.com/user-attachments/files/15531083/overflownTxs-Cardona.json)

Here are all the overflown txs I found for Mainnet and Cardona.
