### ISSUE TITLE
Create technical documentation for CDK Erigon that covers the following

### ISSUE THREAD

**Issue by Sharonbc01** [0xPolygon/cdk-erigon#449]
List all supported RPC functionality (sync modes, Data streamer, UI, RPC methods, etc)

- Provide a brief description of each functional capability
- Configuration options / guidance 

List all supported sequencer functionality (Data streamer, Batch generation / pre execution, special mode, unwind, etc)
- Provide a brief description of each functional capability 
- Configuration options / guidance 

Technical architecture diagram showing components and their inputs and outputs.

**Comment by Sharonbc01** [comment]
Hi @mandrigin @kmurphypolygon, I think this issue has been addressed and can be closed. Do you agree? 

- https://github.com/0xPolygon/polygon-docs/blob/cc6ccd7fac9d1145f3899678a1065774b1611b71/docs/cdk/erigon/chain-config.md
- https://github.com/0xPolygon/polygon-docs/blob/cc6ccd7fac9d1145f3899678a1065774b1611b71/docs/cdk/erigon/deploy-cdk-erigon.md
- https://github.com/0xPolygon/polygon-docs/blob/cc6ccd7fac9d1145f3899678a1065774b1611b71/docs/cdk/erigon/index.md
- https://github.com/0xPolygon/polygon-docs/blob/cc6ccd7fac9d1145f3899678a1065774b1611b71/docs/cdk/erigon/network-recovery.md
- https://github.com/0xPolygon/polygon-docs/blob/cc6ccd7fac9d1145f3899678a1065774b1611b71/docs/cdk/erigon/releases.md
- https://github.com/0xPolygon/polygon-docs/blob/cc6ccd7fac9d1145f3899678a1065774b1611b71/docs/cdk/erigon/resources.md

**Comment by kmurphypolygon** [comment]
@Sharonbc01 yes, I believe so ... but the description structure is a little bit different to how we did it so I wondered if you wanted something else?

**Comment by Sharonbc01** [comment]
Yes will close for now as we can add a technical architecture diagram showing components and their inputs and outputs at a later date.
