### ISSUE TITLE
[Sequencer] Witness generation is inconsistent across Erigon runs on Cardona

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#470]

**Comment by V-Staykov** [comment]
I've tried to reproduce it on Cardona and Bali but unsuccessfully.

**Comment by Sharonbc01** [comment]
@mandrigin is this issue still valid? Can this be closed.

**Comment by Sharonbc01** [comment]
@mandrigin confirmed we can close.
