### ISSUE TITLE
[Sequencer] redundant entries in the datastream & other minor fixes

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#477]
(1) double “batch close”
(2) blockHash is incorrect

**Comment by hexoscott** [comment]
1) should be resolved soon

**Comment by hexoscott** [comment]
2) my understanding here is that fork >= 7 the block hash should be the block root.  I'm unsure what it should be prior to that at the moment

**Comment by krlosMata** [comment]
Previous forks, 1 tx === 1 block.
The blockHash was computed as follows:
- The SR at the very end of the transactions we defined as the blockhash. SR_A
- `SR_A` was saved in the system SC and it produced `SR_B`
- Therefore, `SR_A` is the blockhash and `SR_B` is the final stateRoot

**Comment by hexoscott** [comment]
Ah ok I see, so effectively the block hash is the intermediate root before that value is then added to the SC producing the new state root.  Confusing that it's referred to as the block hash which has a different meaning based on the context, but I think I have the picture now for pre-etrog.  I think the spec will go a long way towards us nailing this

**Comment by mandrigin** [comment]
fixed by #487
