### ISSUE TITLE
[Infra] Deploy protobuf datastream to the integration network 2

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#486]

**Comment by Sharonbc01** [comment]
Hi @eduadiez  assigning you this issue following update with Gateway on CDK Erigon RPC.  @mandrigin noted partners may need a heads up before deployment as could be a breaking change?

**Comment by mandrigin** [comment]
no that is different

**Comment by mandrigin** [comment]
also, it was done

**Comment by Sharonbc01** [comment]
Ah thanks @mandrigin my apologies I mixed up with #463
