### ISSUE TITLE
when I run erigon as zkevm rpc and sync batch from 0 to latest, I got OOM error

### ISSUE THREAD

**Issue by zibuyu28** [0xPolygon/cdk-erigon#491]
#### System information

Erigon version:  branch zkevm

OS & Version: Linux

Commit hash: 

Erigon Command (with flags/config):

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: 

#### Backtrace

````
[backtrace]
````

**Comment by zjg555543** [comment]
**Fixed PR:**
https://github.com/0xPolygonHermez/cdk-erigon/pull/585.


**Root case:**
Using mapmutation consumes too much memory in the regenerateIntermediateHashes function, especially when processing blocks from 0 to the maximum block.

**Test Result:**
Tested on the XLayer Testnet with 8 cores and 64 GB of RAM.
Test branches: https://github.com/okx/xlayer-erigon/pull/18
Old method:
![image](https://github.com/0xPolygonHermez/cdk-erigon/assets/7919751/9f715962-f78e-4247-8099-bb8711fa85c4)

New method:
![image](https://github.com/0xPolygonHermez/cdk-erigon/assets/7919751/76255014-000b-4e55-9928-29e27f7230a8)
