### ISSUE TITLE
[Sequencer, Dupe] Cardona batches are 100% executable with real executor with Erigon

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#495]
Used to track progress for CDK, do not close.

**Comment by Sharonbc01** [comment]
Hi @mandrigin are batches executing on CDK 2 Sepolia Erigon CDK 2 (chain 452)? Can this be closed?

**Comment by Sharonbc01** [comment]
Hi @mandrigin can this now be closed as is seems to have been tested already on CDK 2 integration network.

**Comment by mandrigin** [comment]
done
