### ISSUE TITLE
[Infra] Provision a CDK validium network with cdk-erigon sequencer

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#502]
Should be exactly like Integration Network 2, but using Validium instead of rollup config.

**Comment by Sharonbc01** [comment]
Hi @zuiris assigning this task to you as Igor assumes this is work to be done by the Polygon CDK team.

**Comment by Sharonbc01** [comment]
HI @xavier-romero  I have assigned this to you please as @praetoriansentry mentioned on the daily status call yesterday that your team are happy to set up a CDK (validium) test network for CDK Erigon. Thank you

**Comment by Sharonbc01** [comment]
This was delayed as Xavier had to wait for the new zkevm-sequence-sender. Xavier now has all he needs.

**Comment by Sharonbc01** [comment]
Latest status:  

- CDK1 network has sequence-sender running after setting DAC and resetting whole network. That seems to be working fine.
- Next step that would be Verifying whyL1 is not working because current aggregator(sync library) does not support Validium contracts.

**Comment by Sharonbc01** [comment]
Hi @praetoriansentry & Thiago assigning this to you both to complete

**Comment by Sharonbc01** [comment]
Network now running! Closing this issue.
