### ISSUE TITLE
[Infra] Add nightly LxLy bridge backend tests to work with Erigon sequencer (only ERC-20 and ETH) (Validium)

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#523]
Similar to #468 but for validium instead

**Comment by mandrigin** [comment]
@Sharonbc01 please assign to an appropriate person.

**Comment by Sharonbc01** [comment]
@zuiris FYI Bridge tests

**Comment by mandrigin** [comment]
https://github.com/0xPolygon/jhilliard/blob/main/lxly-bridge-test/test.sh

**Comment by Sharonbc01** [comment]
Assigning to @joanestebanr

**Comment by mandrigin** [comment]
Fixed by: #606
