### ISSUE TITLE
[Infra] Develop and add Message Passing LxLy bridge tests to nightly CI

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#556]

**Comment by Sharonbc01** [comment]
Created a Jira task for this work and looking for  an engineer to work on it.

**Comment by Sharonbc01** [comment]
Confirmed with @revitteth  that he has what he needs for now. Max will resume the nightly testing work once he has solved an issue with the integration network 5 and provide more info

**Comment by Sharonbc01** [comment]
@zuiris confirmed we do require message passing bridge tests.

**Comment by Sharonbc01** [comment]
@zuiris please can these tests be build and passed to Gateway FM for testing CDK network now successfully running

**Comment by mandrigin** [comment]
that is done

**Comment by Sharonbc01** [comment]
Yes it  is done but not verified, it's failing because Network 5 is down. Waiting on @hexoscott to confirm when network 5 back to test. cc: @joanestebanr

**Comment by hexoscott** [comment]
network 5 is now up and running again
