### ISSUE TITLE
[BUG] Integration 5 block hash mismatch

### ISSUE THREAD

**Issue by revitteth** [0xPolygon/cdk-erigon#562]
Erigon sequencer and Erigon RPC nodes disagree at block height: 13060. However, erigon sequencer and zkevm node agree. Seems like an issue with fork enablement in erigon RPC syncing from sequencer datastream.

RPC request:
```
{
  "jsonrpc": "2.0",
  "method": "eth_getBlockByNumber",
  "params": [
    "0x3304",
    true
  ],
  "id": 1
}
```

### Integration 5 Endpoints
- erigon http://34.175.214.161:8500
- zkevm http://34.175.214.161:8505
- sequencer http://34.175.214.161:8005

Diff (erigon sequencer left, erigon rpc right)
![image](https://github.com/0xPolygonHermez/cdk-erigon/assets/693995/ce07a8c0-f9ef-4666-bd38-ed40cda46c64)

Detected via nightly block comparison: https://github.com/0xPolygonHermez/cdk-erigon/actions/runs/9392909479 and further investigated to block height 13060 with `cmd/hack/rpc_compare` (`go run ./cmd/hack/rpc_checker -node1 http://34.175.214.161:8500 -node2 http://34.175.214.161:8505 -fromBlock 13000 -step 1`)

**Comment by mandrigin** [comment]
Probably is related to the unwind we saw before

**Comment by mandrigin** [comment]
Might be related to #555, and the unwinds we see at the start of the RPC nodes sometimes

**Comment by mandrigin** [comment]
I reproduced it on Bali too

### (1) the datastream connection kaput

```
EROR[06-07|16:18:53.960] Error while executing stage              err="[3/16 Batches] l2blocks download routine error: 192.168.1.104:62625 read full L2 blocks error: read file entry error: error reading file bytes: reading from server: read tcp 192.168.1.104:62625->34.142.2.130:6900: read: connection reset by peer"
```

### (2) reconnect fails, wrong block num

```
EROR[06-07|16:18:54.643] Error while executing stage              err="[3/16 Batches] block number is not sequential, expected 1312080, got 1326280"
EROR[06-07|16:18:54.643] Staged Sync                              err="[3/16 Batches] block number is not sequential, expected 1312080, got 1326280"
```


### (3) restart node
everything fine it downloads blocks and executes, state root match, but gasLimit is wrong and blockHashes are wrong forever since

```
python3 compare-rpc.py https://rpc-legacy.internal.zkevm-rpc.com http://127.0.0.1:8545 --block 1312080
block number 1: 1312080	fetched from https://rpc-legacy.internal.zkevm-rpc.com
block number 2: 1312080	fetched from http://127.0.0.1:8545
block number to check 1312080
Full difference between the blocks: {'size': ['0x203', '0x200'], 'gasLimit': ['0x4000000000000', '0x1c9c380'], 'hash': ['0x52c7721da4d2fb1eebd75cb6d6164e92bd319df691c1dd3382b9cb99050d55b6', '0xcca8fb2344cb86e785b25e4a89bb33b78cbbaef52e85c023e3e1fdbcc31ab4ff']}
```
