### ISSUE TITLE
[RPC] Mismatch block hash on XLayer mainnet — Cardona affected too

### ISSUE THREAD

**Issue by zjg555543** [0xPolygon/cdk-erigon#576]
The raw [issue 411](https://github.com/0xPolygonHermez/cdk-erigon/issues/411) was logged first, but it still exists on the **Xlayer mainnet** which used fork.9 during first deployment.

The tx hash: [0x6118d61806013e84408a47bd1bad1e44149534bc2f4b4dae5f440fe11618c579](https://www.oklink.com/xlayer/tx/0x6118d61806013e84408a47bd1bad1e44149534bc2f4b4dae5f440fe11618c579/log)

The result data length for zkEVM is 712; it doesn't pad with zeros to be a multiple of 32, whereas [Erigon](https://github.com/0xPolygonHermez/cdk-erigon/pull/475/files#diff-9b20e8b2175459824599b299c44eb928a1c4bbf34dda479af9845da9b8bac578L234) does.
![image](https://github.com/0xPolygonHermez/cdk-erigon/assets/7919751/c98f951c-ec1d-45a1-81b3-59f92aa09ed5)

**You can get more log more info from zkevm rpc**
```
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x6118d61806013e84408a47bd1bad1e44149534bc2f4b4dae5f440fe11618c579"],"id":1}' https://rpc.xlayer.tech | jq
```

**You can get more log more info from erigon rpc**
```
git clone https://github.com/0xPolygonHermez/cdk-erigon.git
cd cdk-erigon
git checkout  v1.0.10
cp xlayerconfig-mainnet.yaml.example xlayerconfig-mainnet.yaml
make cdk-erigon
./build/bin/cdk-erigon --config="./xlayerconfig-mainnet.yaml"
```

**Comment by mandrigin** [comment]
fixed by https://github.com/0xPolygonHermez/cdk-erigon/pull/588 and https://github.com/0xPolygonHermez/cdk-erigon/pull/595 @zjg555543 please test

**Comment by zjg555543** [comment]
Awesome. I have tested the mainnet on xlayer, and the block results are consistent with zkevm.
Test with our [branch](https://github.com/okx/xlayer-erigon/compare/dev...okx:xlayer-erigon:zjg/mainnet-hash?expand=1), merged the 2 RPs.
