### ISSUE TITLE
[Sequencer] Add HaltOnBatchNumber mechanism

### ISSUE THREAD

**Issue by giskook** [0xPolygon/cdk-erigon#593]
# Rationale

## Why should this feature exist?

zkEVM node has this feature, `Sequencer.Finalizer.HaltOnBatchNumber` can halt sequencer at sepecified batch, so sequencer can stop summit rollups to L1.
## What are the use-cases?
Sometimes especially for significant changes, we have to halt the sequencer and wait all the rollups be summit to L1 and all proofs be verified.

# Implementation
N/A

## Do you have ideas regarding the implementation of this feature?
Some as zkevm-node

## Are you willing to implement this feature?
Y

**Comment by mandrigin** [comment]
@giskook great idea, we would like a conribution for that :)
