### ISSUE TITLE
[Agg] Integrate AggLayer

### ISSUE THREAD

**Issue by giskook** [0xPolygon/cdk-erigon#594]
# Rationale

## Why should this feature exist?
X Layer mainnet submmit proofs to AggLayer. so I think we need support AggLayer as well.

## What are the use-cases?
Integrate AggLayer

# Implementation

## Do you have ideas regarding the implementation of this feature?
Same as zkEVM-node

## Are you willing to implement this feature?
Y

**Comment by mandrigin** [comment]
There is nothing to do from this perspective, this node should be fully compatible with the AggLayer. Its up to the aggregator/prover to be able to post to AggLayer but this is not about cdk-erigon.

**Comment by giskook** [comment]
@mandrigin I think ckd-erigon(aggregator) should send proofs to agglayer?

**Comment by mandrigin** [comment]
aggregator is not a part of cdk-erigon, it is an indepenent component that has nothing to do with this repo ;-D
