### ISSUE TITLE
OOM kill - cdk-erigon is OOM killed in interhashes for large chains

### ISSUE THREAD

**Issue by revitteth** [0xPolygon/cdk-erigon#609]
Initial fix regressed sequencer unwinds: https://github.com/0xPolygonHermez/cdk-erigon/pull/585 and has been reverted.

See: https://github.com/0xPolygonHermez/cdk-erigon/issues/491#issuecomment-2159559920

**Comment by mandrigin** [comment]
fixed, tested on Bali and Cardona
