### ISSUE TITLE
remove or update `WITNESS.md`

### ISSUE THREAD

**Issue by 0xaatif** [0xPolygon/cdk-erigon#648]
https://github.com/0xPolygonHermez/cdk-erigon/blob/43d625fd54b0d96bb08654cb5e9a3ac93199a21f/turbo/trie/WITNESS.md?plain=1#L1

It's not faithful to the implementation, so why keep it?

**Comment by mandrigin** [comment]
well, it might be a bit off, but if you see the exact differences, you are very welcome to contribute to fix them ;-)
