### ISSUE TITLE
[Sequencer] zkevm_getBatchByNumber does not match zkevm node response

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#656]
We discovered during attempting to run a validium network that this call has some inconsistency with the zkevm node version.  The DAC node cannot read the batch from the sequencer because it disagrees with a "hash" there (not sure on the details at the moment).

**Comment by revitteth** [comment]
- [x] - batchl2data
- [ ] - accInputHash
- [x] - ler, ger, rer, mer
- [ ] - verify batch tx hash
- [ ] - response should be null when requesting batch height above node current sync

**Comment by mandrigin** [comment]
fixed by #702 among other fixes
