### ISSUE TITLE
Ability for CDK Erigon to support rollback sequences features

### ISSUE THREAD

**Issue by Sharonbc01** [0xPolygon/cdk-erigon#667]
The CDK Erigon node as a sequencer will need to have the ability to rollback to a specific sequence using the rollback feature introduced in the banana protocol.

# Implementation Guidelines

We use L1 as the source of truth for the rollback sequences.

The expected flow of handling these sequences.

(1) sequencer is stopped manually

(2) sequencer restarted with a special command-line flag `zkevm.rollback.start-from-L1-block: <block_num>`.
Alternatively, the sequencer may monitor rollback event on L1 and automatically rollback when an event is found.

(3) the sequencer will search for the rollback sequence on L1 starting from block <block_num>, until it finds it. the sequencer is not producing blocks at that point in time. if the sequencer reaches the tip of the chain w/o finding any rollback sequencer, it will exit with an error.

(4) when the rollback sequence is found, then sequencer unwinds its state to before the unwound invalid batch, then begin re-sequencing from this batch forward. batch and block numbers are re-used, just like with normal unwinds. 
Ideally, the sequencer should try its best at re-sequencing the transactions. It means that, for any transaction at index i in a rolled back L2 block N, it will be re-sequenced at exactly the same index i and block number N. If it is impossible to re-sequence a transaction under such condition, the sequencer will panic in strict mode, or prints out a warning log in non-strict mode. In terms of implementation, it will be very similar to L1 recovery, except that some conditions may be relaxed, e.g. the block hash of a block may be different due to a corrected GER, the batch number of a block is different after bug fix.

(5) the sequencer adds an "unwind" entry to the datastream (datastream protobuf entry to be designed), and then next batches and entries are added normally. The format of unwind entry could be something similar to the rollback [event](https://github.com/0xPolygonHermez/zkevm-contracts/blob/v7.0.0-rc.1-fork.10/contracts/v2/PolygonRollupManager.sol#L328-L332) in the smart contract.

(6) RPC nodes finding this "unwind" entry, unwind the state accordingly, then continue processing other DS entries as usual (including verification for block and batch numbers, taking into account that they are re-used). 

## Notes

* if the sequencer notes the unhandled rollback sequence while operating normally it should HALT the sequencer with an appropriate log message (that is specific enough to put an alarm on) and stop operating.

**Comment by hexoscott** [comment]
implementation here https://github.com/0xPolygonHermez/zkevm-contracts/blob/v7.0.0-rc.1-fork.10/contracts/v2/PolygonRollupManager.sol#L737

**Comment by hexoscott** [comment]
Design proposal here https://hackmd.io/PDY-iuodSSupZ_L7hlfzQw?view

**Comment by Sharonbc01** [comment]
Tag @hexoscott

**Comment by Sharonbc01** [comment]
@cffls Noting here that the target date to merge pr #894 & pr #886 into the zkEVM main branch and also the upstream branch is **Aug-27** after the sequencer is deployed to Cardona on Aug-26.

**Comment by Sharonbc01** [comment]
@cffls can this issue be closed now?

**Comment by cffls** [comment]
Yes, we can close it.
