### ISSUE TITLE
[Sequencer] single TX that overflows counters causes tight block production loop

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#678]
If we encounter a scenario where a single large TX is enough to overflow gas or counters the sequencer goes into a tight loop of producing a crazy amount of blocks.  We shouldn't do this and need a way to handle this scenario by rejecting the TX from the pool if it is enough to cause this problem.

**Comment by kstoykov** [comment]
@hexoscott 
A single tx that overflow counters is handled correctly after limbo has been merged into zkevm branch. Or at least I thought so. Do you remember what version have you been using when you encounter the issue.

If a tx overflow gas then it is not allowed to tx pool at all. 

If a tx overflow during execution then it is not counted as an error but rather as a reverted tx.

I suppose that there is some other case that I'm missing.
