### ISSUE TITLE
[RPC] RPC node produced a stream with duplicate batch entries in it

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#681]
Unsure of the scenario that caused this to happen, but we have seen this on integration network 5 where batch 10067 appeared at entry 487903 and also 487908 which shouldn't be allowed to happen.

**Comment by Sharonbc01** [comment]
Hey @mandrigin I spotted this issue has no one assigned to it. Please can you review. Thanks

**Comment by Sharonbc01** [comment]
Hey @mandrigin is this still a valid issue or can this be closed please?

**Comment by Sharonbc01** [comment]
@mandrigin confirmed on status call Aug-07 that this issue can now be closed.
