### ISSUE TITLE
[Sequencer] Publish datastream block-by-block when the external executor is set.

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#689]
Basically, use the notion of WIP batch from the legacy node, and send WIP batch to executor first with 1 block, then with 2 blocks, etc…

On each PASS, we publish DS. On FAIL, we unwind and use Limbo.

On sequencer restart we immediately close WIP batch and begin another.

```pseudo
block_number = 1
wip_batch = []

while not is_ready_to_close(wip_batch) do
    block = sequencer.create_block(block_number)
    
    wip_batch.append(block)  // Add new block to WIP batch
    verification_result = external_stateless_executor.verify(wip_batch)
    
    if verification_result == PASS then
        datastream.add_block(block)  // Add verified block to DS
        block_number = block_number + 1
    else
        log_error("Verification failed for block " + block_number)
        break  // Stop the process if verification fails
    end if
end while
```

**Comment by Sharonbc01** [comment]
This is addressed by [Executor block by block #909](https://github.com/0xPolygonHermez/cdk-erigon/pull/909)  @mandrigin confirmed on status call Aug-07 that this issue can be closed.
