### ISSUE TITLE
[Sequencer] check executor results for integration network 3

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#690]
The prover looks to be generating a different state root to that of erigon on integration network 5.

We need to run this network through L1 recovery with an external executor to verify that it agrees / disagrees with the erigon state root for three batches, 1873, 1874, 1875.

Once we have this we can begin working on why our root differs, is it a witness issue or something else?

**Comment by mandrigin** [comment]
It was confirmed its 1874 is the batch with the state root disagreement.

**Comment by mandrigin** [comment]
checked, out of counters, case closed
