### ISSUE TITLE
The data returned by calling the debug_traceTransaction method and the zkevm-rpc are inconsistent.

### ISSUE THREAD

**Issue by rayn316** [0xPolygon/cdk-erigon#704]
#### System information

Erigon version: latest

OS & Version: ubuntu 22.04

Commit hash: 

Erigon Command (with flags/config):

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: cardona

#### Actual behaviour
Compare the results when requesting the image. The data returned may be different in certain blocks.
![image](https://github.com/0xPolygonHermez/cdk-erigon/assets/24621599/4f110a2f-343d-43e2-8e04-571ce9b31a2b)
![image](https://github.com/0xPolygonHermez/cdk-erigon/assets/24621599/9634f398-b066-4af4-ad8f-d62c968b6c43)

#### Steps to reproduce the behaviour
Use requests to make requests to zkevm-rpc and cdk-erigon nodes, and compare the returned results.
```
curl --location --request POST 'http://ip:8545' \
--header 'Content-Type: application/json' \
--data-raw '{
    "method": "debug_traceTransaction",
    "params": [
        "0xd39b8fc23465bbbbd1ff5e564bd0aef9bc27428abeb2eb0f19278eb9022559b6",
        {
            "tracer": "callTracer"
        }
    ],
    "id": 1,
    "jsonrpc": "2.0"
}'
```

#### Backtrace

````
[backtrace]
````

**Comment by mandrigin** [comment]
@rayn316 thanks, we will investigate. which chain is that?

**Comment by rayn316** [comment]
chain: cardona  testnet

**Comment by mandrigin** [comment]
which zkevm-rpc URL are you using?

**Comment by rayn316** [comment]
Self-run node: `docker run -d -p 31881:8545 -p 31882:8546 --name polygon-cardona-t1 -v /node/full/polygon-zkevm-cardona/cdk-erigon-data/:/home/erigon/.local/share/erigon hermeznetwork/cdk-erigon --config="./cardona.yaml" --zkevm.l1-rpc-url=http://de-node.blockpi.me/sepolia/http --rpc.gascap=600000000 --rpc.evmtimeout=30s --rpc.batch.limit=100 --rpc.returndata.limit=104857600 --txpool.globalslots 1000000 --txpool.globalbasefeeslots 3000000 --txpool.globalqueue 3000000 --http=true --http.api 'eth,net,web3,debug,trace,txpool' --http.corsdomain '*' --http.vhosts '*'`

**Comment by mandrigin** [comment]
okay, and for zkevm-node?

**Comment by rayn316** [comment]
Default configuration for zkevm-node, docker compose `/app/zkevm-node run --network cardona --cfg /app/config.toml --components rpc --http.api='eth,net,web3,debug,zkevm,trace,txpool'`

**Comment by V-Staykov** [comment]
@rayn316 could you give us the exact tx you queried to get the differences? The one in the example seems to be for different one.

**Comment by rayn316** [comment]
> @rayn316 could you give us the exact tx you queried to get the differences? The one in the example seems to be for different one.

I didn't understand the meaning of this sentence.

This results in variations in the responses after requests from different clients.
```
{
    "method": "debug_traceTransaction",
    "params": [
        "0x6602329c7ac5a8b189bfd0a22bb71f205dc5a9693617f126a34057a216816ca8",
        {
            "tracer": "callTracer"
        }
    ],
    "id": 1,
    "jsonrpc": "2.0"
}
```


The following is capable of returning the same results across different clients.
```
{
    "method": "debug_traceTransaction",
    "params": [
        "0xd39b8fc23465bbbbd1ff5e564bd0aef9bc27428abeb2eb0f19278eb9022559b6",
        {
            "tracer": "callTracer"
        }
    ],
    "id": 1,
    "jsonrpc": "2.0"
}
```

**Comment by rayn316** [comment]
> @rayn316 could you give us the exact tx you queried to get the differences? The one in the example seems to be for different one.

I didn't understand the meaning of this sentence.

This results in variations in the responses after requests from different clients.
```
{
    "method": "debug_traceTransaction",
    "params": [
        "0x6602329c7ac5a8b189bfd0a22bb71f205dc5a9693617f126a34057a216816ca8",
        {
            "tracer": "callTracer"
        }
    ],
    "id": 1,
    "jsonrpc": "2.0"
}
```


The following is capable of returning the same results across different clients.
```
{
    "method": "debug_traceTransaction",
    "params": [
        "0xd39b8fc23465bbbbd1ff5e564bd0aef9bc27428abeb2eb0f19278eb9022559b6",
        {
            "tracer": "callTracer"
        }
    ],
    "id": 1,
    "jsonrpc": "2.0"
}
```

**Comment by V-Staykov** [comment]
@rayn316 we've found part of the issue on our side and will fix it. The problem with the differing inputs and gas though might be with zkevm-node since our data matches what we expect. We are discussing it currently.

**Comment by rayn316** [comment]
Okay, thank you for your explanation.
