### ISSUE TITLE
[Tracing] 0x5ca1ab1e Tx No not updated before tracing tx (debug_traceTransaction)

### ISSUE THREAD

**Issue by revitteth** [0xPolygon/cdk-erigon#72]
The storage location for the txno is not updated before a tx is traced.

e.g. block 7006434, opcode NUMBER at 362271 gas pushes 7006433 instead of 7006434

**Comment by V-Staykov** [comment]
The issue here is the same as https://github.com/0xPolygonHermez/cdk-erigon/issues/73

We have to add the state updates before block execution in the tracing as well.
