### ISSUE TITLE
[RPC] zkevm_getBatchWitness requires performance optimization

### ISSUE THREAD

**Issue by LeoGuo621** [0xPolygon/cdk-erigon#720]
# Rationale
zkevm_getBatchWitness uses the `getAllBlocksInBatchNumber` function, which traverses from the latest batch to the target batch. In the worst case, it will traverse all batches, affecting query performance.

```
func getLastBlockInBatchNumber(tx kv.Tx, batchNumber uint64) (uint64, error) {
	c, err := tx.Cursor(hermez_db.BLOCKBATCHES)
	if err != nil {
		return 0, err
	}
	defer c.Close()
	var k, v []byte
	for k, v, err = c.Last(); k != nil; k, v, err = c.Prev() {
		if err != nil {
			return 0, err
		}
		val := hermez_db.BytesToUint64(v)
		if val == batchNumber {
			return hermez_db.BytesToUint64(k), nil
		}
	}

	return 0, nil
}
```

# Implementation
Perhaps we can optimize it with the idea of binary search.

**Comment by kstoykov** [comment]
This performance issue is resolved in latest versions.
