### ISSUE TITLE
[Sequencer] Counter maximum values incorrect

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#732]
We need to update our counters to new maximum values:
https://github.com/0xPolygonHermez/zkevm-commonjs/blob/feature/v6.3.0-fork.9/src/virtual-counters-manager.js#L28
https://github.com/0xPolygonHermez/zkevm-rom/blob/main/main/constants.zkasm#L106

**Note the 5% safe range on the above**

> The exact counters will be:
> Steps: 7968988
> Arith: 249037
> Binary: 498074
> memAlign: 249037
> keccak: 2258
> padding: 142307
> poseidon: 265639
> sha256: 1769

**This only applies for counters for <= fork 9**

**Comment by hexoscott** [comment]
On the 5% safety.  This is the original steps of (2**23 - 200) *.05.  There is a constant -200 applied to the original steps value that we need to take into consideration also

**Comment by mandrigin** [comment]
fixed by #742
