### ISSUE TITLE
[RPC] WS server never implements ws namespace configurations

### ISSUE THREAD

**Issue by sieniven** [0xPolygon/cdk-erigon#737]
## Context

- RPC server when websocket is enabled (ws: true) never implements websocket namespace configurations
- Ws namespace configurations are also not specified on the node's flags
- The API handler of the RPC server will serve on the HTTP endpoint specified with HTTP namespace configs, not on ws namepace configs
- Full context of the issue: https://github.com/okx/xlayer-erigon/compare/dev...okx:xlayer-erigon:niven/fix-ws?expand=1

**Comment by mandrigin** [comment]
Hey!

thanks!

always happy to get a contribution for that
