### ISSUE TITLE
[Tracing] Effective Gas Percentage not applied when tracing

### ISSUE THREAD

**Issue by revitteth** [0xPolygon/cdk-erigon#74]
Requires some confirmation, but the EGP should be applied in tracing as well as execution.

Example:
Testnet, block 916581, gas usage 158313 != gas usage reported by debug_traceTransaction 158313

**Comment by revitteth** [comment]
It appears EGP is applied in `callManyTransactions`:

```		
// now read back the effective gas price and set it for execution
effectiveGasPricePercentage, err := api.getEffectiveGasPricePercentage(dbtx, hash)
if err != nil {
	return nil, err
}
msg.SetEffectiveGasPricePercentage(effectiveGasPricePercentage)
```

However, there may be another place we need to repeat the logic - continuing the search.

**Comment by V-Staykov** [comment]
The problem actually is not with effective gas percentage. It is being calculated for all traces.

The gas difference came from intrinsic gas being calculated before the tracer was initialized in `ApplyMessage`. That made it so in traces the gas set was the actual minus the intrinsic.
