### ISSUE TITLE
[Sequencer] we need to ensure we use a size cap when running in a validium context

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#751]
We have a batch data size for rollups that works in a similar way to the batch counters.  We need to ensure we are using a cap when running in a validium context.  We need to check what the limitations are for this as it might not affect the sequencer.

**Comment by mandrigin** [comment]
yeah, add flag to the maximum number of blocks in batch for validium

**Comment by hexoscott** [comment]
Closing as this rule only applies to the sequence sender, it limits the number of batches it can send to the L1 to 300.  So long as the sequencer is following the rules on counters and also batchL2Data size, which it already is, there is nothing more to do on the sequencer side.
