### ISSUE TITLE
[txpool] Miss a threshold gas price to restrict txs from entering the txpool.

### ISSUE THREAD

**Issue by LeoGuo621** [0xPolygon/cdk-erigon#764]
# Rationale
In `zkevm-node`, we use `minSuggestedGasPrice` to restrict low gas price txs from entering the pool ([zkevm/pool/pool.go:509](https://github.com/0xPolygonHermez/zkevm-node/blob/ac8a7e9587bc25f13460c12bba5bac1877fd6bf3/pool/pool.go#L509)).
The `minSuggestedGasPrice` is a dynamically changing value that periodically updates based on the minimum gas price in the pool over a recent period.
However, in `cdk-erigon`, when [addTxs](https://github.com/0xPolygonHermez/cdk-erigon/blob/6512d15b68ce5dd215a8f38cf438fbc959725e07/zk/txpool/pool.go#L992) to pool, I haven't found any logic that restricts low gas price txs from entering the pool.

# Implementation
Perhaps we need to implement in cdk-erigon the feature from zkevm-node that restricts txs with low gas prices in the txpool.

**Comment by hexoscott** [comment]
We have code now that ensures calls like eth_gasPrice will not go lower than the value that will be accepted into the txpool.  This is driven by the `zkevm.default-gas-price` flag which defaults to 0.01gwei.  I'm closing this issue as I believe that addresses this problem, but please re-open if there is something more to do here.
