### ISSUE TITLE
[RPC] The blockhash mismatches between Erigon and zkEvm node eth_getBlockByNumber

### ISSUE THREAD

**Issue by V-Staykov** [0xPolygon/cdk-erigon#77]
This issue is detected on mainnet block 948546, but occurs on other blocks as well.

The responce from the RPCs of Erigon and zkEvm for eth_getBlockByNumber return different blockhashes. The traceRoot does not match as well.

After some investigation it seems one of the logs in the tx has difference in it's data field.

**Comment by antdanchenko** [comment]
Please note that parentHash is also different in the response from Erigon, e.g. 
```
E   Failed: block: 3862508
E   '0x3a1d6a6b77794ce1b10b9c0a26e85fe282076780a051be011c610c4dc4bf6c1f' for 'hash', expected '0x431c5474ce6bc3473416dd0843deeaa169a74772346da2f5def893e3d948decb'
E   '0xe2de83f5fe69fab8a9e109711e89d403054cf62076778d1abffd212c0cdf940c' for 'parentHash', expected '0xc7937d04d462aa1e0deb39a2b7e2482c39509ab0e761093ec3340b5a0f8621cc'
```

**Comment by revitteth** [comment]
Awaiting input about zkevm-node possible issue.
