### ISSUE TITLE
[Sequencer/RPC] - getBatchWitness cache behaviour change

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#771]
By default the RPC call will always regenerate the witness if either `partial` or `full` are passed as the 2nd argument.  This is causing unnecessary work by the sequencer as a lot of tooling sends `partial` by default as the 2nd argument.

We need to introduce `partial-regen` and `full-regen`.  If these are used then we force the regeneration.

If a request arrives with just `partial` and the node is configured with `zkevm.witness-full: false` then we know we can just return the cached value, and vice versa for `full` and `zkevm.witness-full: true`.  If the node is configures with `zkevm.witness-full: false` and `full` is sent then this will be a cache miss and will cause a regeneration.

**Comment by mandrigin** [comment]
Why this change? Because of the non-obvious behaviour it looks like aggregator always tries to regenerate witnesses from scratch, that takes a lot of time.
