### ISSUE TITLE
Base fee calculation error on pre-london fork

### ISSUE THREAD

**Issue by sieniven** [0xPolygon/cdk-erigon#773]
## Summary

- When the chain is on pre-london fork (pre EIP 1559), base fee calculations defaults to return INITIAL_BASE_FEE:https://github.com/0xPolygonHermez/cdk-erigon/blob/479635953bfa8335d36f2d8e589d100193b9748e/params/protocol_params.go#L124
- Seems like cdk-erigon does not handle EIP1559 transactions anyway:
https://github.com/0xPolygonHermez/cdk-erigon/blob/479635953bfa8335d36f2d8e589d100193b9748e/zk/txpool/pool.go#L710-L713

## Context
 - The notifications accumulator pipeline will calculate the current block's base fee with [CalcBaseFeeZk](https://github.com/0xPolygonHermez/cdk-erigon/blob/zkevm/consensus/misc/eip1559_zk.go). However, the function calls CalcBaseFee, which assumes that the chain is on post London fork
 - This is problematic because base fee is never set on blocks pre-london fork. In addition, the accumulator channel propagates the initial base fee to the txpool, thus setting the pendingBaseFee on the pool to be INITIAL_BASE_FEE
 - Any txs with gas price below INITIAL_BASE_FEE will never be promoted to the pending pool from the baseFee pool

**Comment by sieniven** [comment]
#774 resolves this issue by adding a forkguard on CalcBaseFeeZk to check for pre/post london fork. cc/ @revitteth

**Comment by hexoscott** [comment]
We now have code in place to handle the base fee differently which uses the value from `zkevm.default-gas-price` instead.  This will ensure the node won't return a gas price lower than this value from eth_gasPrice and will stop transactions getting stuck in the base fee pool.  I'm closing this issue now, but please re-open if we have missed something.
