### ISSUE TITLE
[docker] Enable use of vectorized poseidon in the Alpine container

### ISSUE THREAD

**Issue by revitteth** [0xPolygon/cdk-erigon#78]
Currently an error occurs when using vectorized poseidon library on Alpine due to issues with dependencies:

```"Step #2 - "build": #14 185.6 /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/gateway-fm/vectorized-poseidon-gold@v0.1.2/src/vectorizedposeidongold/../../build/linux/libomp.so: undefined reference to `strcpy@GLIBC_2.2.5'"```

**Comment by revitteth** [comment]
@kstoykov will complete this by writing the C++ impl into C so it can be compiled by CGO

**Comment by kstoykov** [comment]
It works on alpine after commit be7194cd42fb45f173351d0b026a356e8d0c6084
