### ISSUE TITLE
[Sequencer] - transient error handling when requesting data from the executor needs improving

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#790]
We ran into a problem today where the Bali sequencer was in a loop reporting about a bad batch.  After some investigation I found that the sequencer attempted to send a payload to the executor which failed and it was never attempted again.  We can't let this happen as executors will go offline from time to time, we must retry this with brief pauses until an executor is available again.

**Comment by kstoykov** [comment]
Could you attach logs once we they are available

**Comment by hexoscott** [comment]
{
	"id": "AgAAAZCx8YIDH7jIGwAAAAAAAAAYAAAAAEFaQ3g4WTUxQUFBX1N0Z2VNdjFjTUFBSgAAACQAAAAAMDE5MGIxZjUtN2ZkZC00NGQ3LTk4NDYtYjNiNmE2Mjc1NzQ3",
	"content": {
		"timestamp": "2024-07-14T15:51:53.091Z",
		"tags": [
			"dirname:/var/log/pods/zkevm_sequencer-erigon-statefulset-0_9f153a3e-c334-4c08-b63e-6c988703a578/sequencer-erigon",
			"cloud:gcp",
			"container_name:sequencer-erigon",
			"kube_stateful_set:sequencer-erigon-statefulset",
			"kube_namespace:zkevm",
			"display_container_name:sequencer-erigon_sequencer-erigon-statefulset-0",
			"image_id:docker.io/hermeznetwork/cdk-erigon@sha256:962a96f7f2150c33c156cabce88c6726d1fc13cd11545b4dda53b0c16365d987",
			"kube_qos:burstable",
			"short_image:cdk-erigon",
			"kube_app_managed_by:helm",
			"env:internal",
			"kube_app_version:0.1.0",
			"project:zkevm",
			"container_id:741006c817fb0e9629eaa5ae2f437c5c4b0d9de28f24625ca4dda51c9c7bc9d3",
			"pod_name:sequencer-erigon-statefulset-0",
			"kube_ownerref_name:sequencer-erigon-statefulset",
			"kube_app_instance:erigon-sequencer",
			"kube_ownerref_kind:statefulset",
			"pod_phase:running",
			"kube_app_name:sequencer-erigon",
			"service:zkevm-internal",
			"persistentvolumeclaim:erigon-datadir-vol-sequencer-erigon-statefulset-0",
			"image_tag:2.0.0-beta10-amd64",
			"source:sequencer-erigon",
			"image_name:hermeznetwork/cdk-erigon",
			"filename:0.log",
			"kube_container_name:sequencer-erigon",
			"datadog.submission_auth:api_key",
			"cluster-location:europe-west2",
			"cluster-name:zkevm-internal",
			"cluster-uid:feb8f81698ea44d78cb938e4e20831b96037bede582f4cd1aa2dd6eb3872c85a",
			"cluster_name:zkevm-internal",
			"instance-id:2879185648426097701",
			"internal-hostname:gke-zkevm-internal-pool-rpc-erigon-5d0b673b-ptq4.europe-west2-c.c.prj-polygonlabs-zkevm-test.internal",
			"kube_cluster_name:zkevm-internal",
			"numeric_project_id:815016926199",
			"project:prj-polygonlabs-zkevm-test",
			"zone:europe-west2-c"
		],
		"host": "gke-zkevm-internal-pool-rpc-erigon-5d0b673b-ptq4.europe-west2-c.c.prj-polygonlabs-zkevm-test.internal",
		"service": "zkevm-internal",
		"message": "[Verifier] Error",
		"attributes": {
			"lvl": "eror",
			"err": "failed to process stateless batch: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.8.0.91:50071: connect: connection refused\"",
			"t": "2024-07-14T15:51:52.769784641Z"
		}
	}
}

**Comment by hexoscott** [comment]
That's the last log which shows the error, there were no more attempts at sending the batch

**Comment by kstoykov** [comment]
Do we have logs for last, let's say, 5-10 minutes before the node stopped? I'm asking because so far I found only one possible way that this could happen and I would to verify it using the logs

**Comment by kstoykov** [comment]
I tried to simulate the issue by using a wrong IP address of an executor. The initial logs are:

```
[INFO] [07-16|06:46:09.626] [7/14 SequenceExecutorVerify] Starting sequencer verify stage 
[EROR] [07-16|06:46:09.626] error on our end while preparing the verification request, re-queueing the task err="no executor available"
[INFO] [07-16|06:46:09.626] [7/14 SequenceExecutorVerify] Finished sequencer verify stage 
[EROR] [07-16|06:46:09.626] Error while executing stage              err="[7/14 SequenceExecutorVerify] error: batch 2 couldn't be processed in 30 minutes"
[EROR] [07-16|06:46:09.626] Staged Sync                              err="[7/14 SequenceExecutorVerify] error: batch 2 couldn't be processed in 30 minutes"
[INFO] [07-16|06:46:10.127] [7/14 SequenceExecutorVerify] Starting sequencer verify stage 
[EROR] [07-16|06:46:10.127] error on our end while preparing the verification request, re-queueing the task err="no executor available"
[INFO] [07-16|06:46:10.127] [7/14 SequenceExecutorVerify] Finished sequencer verify stage 
[EROR] [07-16|06:46:10.127] Error while executing stage              err="[7/14 SequenceExecutorVerify] error: batch 2 couldn't be processed in 30 minutes"
[EROR] [07-16|06:46:10.127] Staged Sync                              err="[7/14 SequenceExecutorVerify] error: batch 2 couldn't be processed in 30 minutes"
```

Then I stopped it and started it again to check if we lose a batch. The results shows that this batch is added to the queue again and failing because of the wrong IP that I was using

```
[INFO] [07-16|06:50:10.370] [7/14 SequenceExecutorVerify] Starting sequencer verify stage 
[EROR] [07-16|06:50:10.371] error on our end while preparing the verification request, re-queueing the task err="no executor available"
[INFO] [07-16|06:50:10.371] [7/14 SequenceExecutorVerify] Finished sequencer verify stage 
[EROR] [07-16|06:50:10.371] Error while executing stage              err="[7/14 SequenceExecutorVerify] error: batch 2 couldn't be processed in 30 minutes"
[EROR] [07-16|06:50:10.371] Staged Sync                              err="[7/14 SequenceExecutorVerify] error: batch 2 couldn't be processed in 30 minutes"
```

I checked the code and we have logic that handles exactly this case. Maybe something else have happened. More logs will be useful.

**Comment by hexoscott** [comment]
This is fine if the executor isn't available at the time, we put some code in to handle that.  But a genuine failure in the send causes problems:

![image](https://github.com/user-attachments/assets/82ebacd3-c0f7-45fe-9e08-139a39cc0c82)

**Comment by hexoscott** [comment]
That will freeze the node and it won't progress

**Comment by kstoykov** [comment]
One of the stages will freeze if all executors has been offline for 30 minutes. In this case there will be a special log. In this case the node can be restarted and everything will be fine. 

Based on the only log that we have this is not the case and something else could have broken the node.

**Comment by kstoykov** [comment]
Fixed in latest versions
