### ISSUE TITLE
Fix cold address access

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#795]
Details: https://hackmd.io/O4t3Xvj9TIydY9UsXfXHiA?view#Fix-cold-address-access

**Comment by Sharonbc01** [comment]
Hi @cffls is this issue still required or does your solution address all our requirements to support the rollback feature in Banana?

**Comment by Sharonbc01** [comment]
Hey @mandrigin who can work on this issue please to support Banana changes?

**Comment by cffls** [comment]
After forkid 12, we should take snapshot **after** adding address to access list. 
Here is the current order [here](https://github.com/0xPolygonHermez/cdk-erigon/blob/d26a959607c0fc880892e0293b47d4514e5fb6e7/core/vm/evm_zkevm.go#L115-L127).
The correct order after forkid 12 should look like [this](https://github.com/erigontech/erigon/blob/release/2.60/core/vm/evm.go#L393-L405).

**Comment by hexoscott** [comment]
https://github.com/0xPolygonHermez/cdk-erigon/pull/973 PR for the change @cffls

**Comment by mandrigin** [comment]
fixed by https://github.com/0xPolygonHermez/cdk-erigon/pull/973
