### ISSUE TITLE
Blockhash padding 32 bytes

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#796]
Details: https://hackmd.io/O4t3Xvj9TIydY9UsXfXHiA?view#Fix-issues-geth-blockhash-padding-32-bytes

**Comment by Sharonbc01** [comment]
Hi @cffls is this issue still required or does your solution address all our requirements to support the rollback feature in Banana?

**Comment by Sharonbc01** [comment]
Hey @mandrigin who can work on this issue please to support Banana changes?

**Comment by mandrigin** [comment]
already fixed here a while ago
https://github.com/0xPolygonHermez/cdk-erigon/blob/92e7d22534bc103203a4a699b8de60a4a5df4c3e/core/types/log_zkevm.go#L44C19-L44C29
