### ISSUE TITLE
memory leak of rpc node

### ISSUE THREAD

**Issue by louisliu2048** [0xPolygon/cdk-erigon#799]
#### System information

Erigon version: `./erigon --version`

OS & Version: Windows/Linux/OSX

Commit hash: 

Erigon Command (with flags/config):

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: 

#### Actual behaviour
RPC node will exit after about 17 mins if I do some stress test and send lots of txs to this node:
<img width="1720" alt="image" src="https://github.com/user-attachments/assets/7c4fae51-14ee-4129-baf7-ab62f4ad1eb9">

#### Backtrace

when we check the log of rpc node ,we will find that the txpool looks not working correctly, it only cache 0 txs in memory, but use about 4.1GB memory(maybe the os kill this docker image for use too much memory)
````
[INFO] [07-16|10:25:07.299] [6/16 Execution] Short circuit           batch=263 block=270
[INFO] [07-16|10:25:07.304] [6/16 Execution] Blocks execution        from=269 to=270
[INFO] [07-16|10:25:07.663] [p2p] GoodPeers
[INFO] [07-16|10:25:07.697] [txpool] stat                            pending=0 baseFee=0 queued=0 alloc=2.6GB sys=4.1GB
````

**Comment by V-Staykov** [comment]
Can you still reproduce this? We've fixed some issues with gas estimation that might've caused this.

**Comment by revitteth** [comment]
@louisliu2048 quick ping to see if this is still reproducible? If not let's close :)

**Comment by hexoscott** [comment]
Closing as stale
