### ISSUE TITLE
[Sequencer] - ability to pause sequencer producing batches

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#805]
During network upgrades we need to ask the sequencer to stop producing batches.  Ideally this would be a "hot" change that can be turned on and off via the RPC.  Maybe a new endpoint zkevm_stopBuilding which will stop the next batch being produced when the loop goes round and just cycle until the node is stopped or the stop building flag is removed.

We want to ensure that we log that this is happening as well to make it obvious why a sequencer has stopped.

**Comment by mandrigin** [comment]
you know that with the current design you can just shut down the stateless executors and the network will halt :-P

**Comment by hexoscott** [comment]
We can, but it might halt mid batch in our sequencer, and we need to ensure that all batches in the network have been sent to the L1 at least by the sequence sender.  The fork change event has a 'lastBatchSequenced' number so we want to ensure that is accurate when we wake the sequencer back up again.
