### ISSUE TITLE
[Sequencer] - L1 recovery speed up

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#806]
During L1 recovery we specify a single L1 block height, this is used for syncing L1 info tree events and also transaction/batch data.  This really slows down the process because we're pulling transaction/batch data for batches that may well already exist in the DB if the node has been "pre-synced" as an RPC using zkevm.sync-limit flag before recovery.

By separating these two flags we can ensure that the Info tree indexes will be correct from the get go and that we pull the minimal amount of block information from the L1.

**note:** now that we are syncing the info tree even as an RPC node this might be a simpler task but we need to check on this.

**Comment by Sharonbc01** [comment]
Hi @mandrigin this issue is one that is required by Edu to go to Cardona, Please can you review and assign. Thanks

**Comment by Sharonbc01** [comment]
Confirmed with @mandrigin this can be closed.
