### ISSUE TITLE
[Sequencer/RPC] - unwind feature not working fully

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#807]
When using the unwind tool at `./cmd/integration` the node looks like it has unwound to the correct height but upon starting the node again too many blocks have been removed.  Having this feature fully working would be a huge help during L1 recovery as you wouldn't need to sync a node from scratch up to the broken batch point, which is typically very close to the tip anyway.

**Comment by Sharonbc01** [comment]
Hey @V-Staykov any update on this issue? Can it be addressed by Aug-09 when we plan to build image for sequencer to deploy to Cardona on Aug-12.

**Comment by hexoscott** [comment]
A quick update on this one, the process appears to be working fine for RPC and sequencer for a simple network, but there are some changes coming as part of other work to handle the unwind of the L1 info tree index which will be crucial for this to be considered complete.  Once we have that we will be able to test some more complex scenarios and ensure things are working as expected.

**Comment by Sharonbc01** [comment]
Thanks @hexoscott for update. 
As noted above this is a requirement from Edu so can this changes coming as part of other work to handle the unwind of the L1 info tree index which will be crucial for this to be considered complete. Do you have an ETA on these? 

I will highlight to @mandrigin at next status update WRT to the target date of Aug-12

**Comment by hexoscott** [comment]
We are aiming to merge in the block by block changes, which include these unwind changes around the info tree, today or tomorrow.  After that we can start testing some more complex unwind scenarios and go from there with any findings we make.

**Comment by Sharonbc01** [comment]
Thanks @hexoscott for getting [Executor block by block #909](https://github.com/0xPolygonHermez/cdk-erigon/pull/909) is merged. Hoping this one can closed soon now you can do more testing with  at a block level for unwinds. Thanks

**Comment by mandrigin** [comment]
fixed by #936
