### ISSUE TITLE
add zkevm_getExitRootTable

### ISSUE THREAD

**Issue by mandrigin** [0xPolygon/cdk-erigon#817]
In the legacy node, it is possible to get to the `exit_root` table to see the full list of exit roots.

In the current node, we have these debug log entries.

```
DBUG[07-10|19:46:31.533] New L1 Index                             index=330 root=0x4de0531c041235e61d768479dbc33eb75375f14a43a53444b5a82a5d406556ac mainnet=0x9d821feaef0089d1c6342ac665c820ecb2797cdeb608108cda3a110a6506b376 rollup=0x7b661280abf3f1f1b6e704daa3b1afcb7c896209b4eedd88ed52a71ce44952f5 ger=0xc23458a3a8c82b917ac18e7e3adee9ff79dcf2bc9a497e81da996cf90879bb10 parent=0xc7c24a4567977225aae53ae51cc721b95e6193bd4b717a397ee048bc6a3eb33b
```

We need to make an RPC method to simplify debugging, that returns full contents of the exit root table.

**Comment by Sharonbc01** [comment]
@mandrigin confirmed on status call Aug-07 that this issue can be closed.
