### ISSUE TITLE
Datastream corruption

### ISSUE THREAD

**Issue by Sharonbc01** [0xPolygon/cdk-erigon#832]
#### System information

Erigon version: `./erigon --version`

OS & Version: Windows/Linux/OSX

Commit hash: 

Erigon Command (with flags/config):

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: 

#### Backtrace

````
[backtrace]
````

**Comment by Sharonbc01** [comment]
Fran has fixed datastream error, testing on mtest integration network: confirming if fix is in forkid9 or forkid 11.

cc: @eduadiez @fractasy

**Comment by agnusmor** [comment]
Fix is in forkid9

**Comment by Sharonbc01** [comment]
Hey @agnusmor we need an update by 7/30 on if this fix is in and complete for this milestone RPC to mainnet. Thanks

**Comment by agnusmor** [comment]
Hi @Sharonbc01, node version [v0.7.1](https://github.com/0xPolygonHermez/zkevm-node/releases/tag/v0.7.1) has been released and it contains the fix for this issue. Cardona network has been updated to this version

**Comment by Sharonbc01** [comment]
Thanks @agnusmor. 

I am also noting here your confirmation on that you have observed it fixes the problem when updating the datastream file when the sequencer starts. The problem was that in some cases it could add a wrong "batch end" entry and that could cause an error in the erigon-rpc side and break the synchronization. Fran tested that this doesn't happen now with the fix and Fran also executed tests to check that everything continues working fine
