### ISSUE TITLE
zkevm_getBatchByNumber method handler issue

### ISSUE THREAD

**Issue by C7-C5** [0xPolygon/cdk-erigon#845]
[Untitled.log](https://github.com/user-attachments/files/16377976/Untitled.log)

The system has experienced a series of failures related to the method zkevm_getBatchByNumber. Calling this method triggers a panic due to a runtime error indicating an invalid memory address or a null pointer dereference.

Software:

> 0xpolygon/cdk-data-availability:"0.0.7"
> hermeznetwork/cdk-erigon:"2.0.0-beta5"
> hermeznetwork/zkevm-prover:"v6.0.3-RC18"
> hermeznetwork/zkevm-sequence-sender:"v0.2.0-RC5"
> hermeznetwork/cdk-erigon:"zkevm-3b0efac-amd64"
> hermeznetwork/zkevm-aggregator:"v0.0.2-RC33"
> hermeznetwork/zkevm-bridge-service:"v0.4.3-RC1"
> hermeznetwork/zkevm-bridge-ui:"etrog-v2"

**Comment by V-Staykov** [comment]
This issue is already fixed, but not yet into a release.
