### ISSUE TITLE
[RPC] `eth_getTransactionByHash` returns an error (txpool disabled) rather than `null` if tx is not in state

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#859]
#### System information

Erigon version: `hermeznetwork/cdk-erigon:beta13-candidate3-5225235-amd64`

OS & Version: `Linux straylight 6.9.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.11-1 (2024-07-25) x86_64 GNU/Linux`

Commit hash: 

Erigon Command (with flags/config): `cdk-erigon --pprof=true --pprof.addr 0.0.0.0 --config /etc/cdk-erigon/config.yaml`

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: kurtosis devnet

#### Expected behaviour

Request:
```json
{
    "id": 0,
    "jsonrpc": "2.0",
    "method": "eth_getTransactionByHash",
    "params": [
        "0x0000000000000000000000000000000000000000000000000000000000000000"
    ]
}
```

Should return:
```json
{
    "id": 0,
    "jsonrpc": "2.0",
    "result": null
}
```

#### Actual behaviour

If the request is made to a node with `txpool.disabled: true` we get the following response:

```json
{
    "error": {
        "code": -32000,
        "message": "TxPool Disabled"
    },
    "id": 0,
    "jsonrpc": "2.0"
}
```

Since disabling the txpool is the recommended configuratoin for the RPC (non-sequencing) nodes, we should make sure the behaviors for handling missing tx hashes align.

#### Steps to reproduce the behaviour

```
cast tx --rpc-url http://127.0.0.1:8545 0x0000000000000000000000000000000000000000000000000000000000000000
```

**Comment by mandrigin** [comment]
okay that is only for txs that don't exist in the state, right?

**Comment by praetoriansentry** [comment]
Yes that's correct. If the transaction has been mined and exists in the historical data, it seemed like it works fine.
