### ISSUE TITLE
The unwind feature to be validated as working on Bali required for release to cardona.

### ISSUE THREAD

**Issue by Sharonbc01** [0xPolygon/cdk-erigon#865]
# Rationale

Why should this feature exist?
What are the use-cases?

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by Sharonbc01** [comment]
Hey @hexoscott JFYI this is required for the sequencer to be deployed to Cardona. I see you are working on #807 related to this.
Do you know when you expect #807 to be completed.

**Comment by hexoscott** [comment]
Hi @Sharonbc01 - I'm working on this at the moment, I'm hoping to have the task completed some point mid next week, 7th August approx.

**Comment by Sharonbc01** [comment]
Thanks @hexoscott that works as our target date for sequencer image for Cardona is Aug-09 and to deploy on Aug-12

**Comment by Sharonbc01** [comment]
@praetoriansentry  the fixing unwinds #936 issue is now resolved, can your team test this on Bali to validate please.

**Comment by hexoscott** [comment]
Following up from our meeting today.  The steps for testing this are:
- sync any network for a while or perform L1 recovery to a set batch height (L1 recovery only works beyond etrog so might need to use an integration network for this)
- run the unwind to a batch lower than current progress (steps below)
- re-run step 1 either syncing as RPC from the DS or running recovery again
- verify that the block details haven't changed for the re-synced data

To run the unwind:
- run `go run ./cmd/integration state_stages_zkevm --datadir=/path/to/dir --chain=hermez-cardona  --unwind-batch-no=56845` subbing in the values for your network
- caveat: if using an integration network the config files for this will need to be in the root of the repo or relative to the binary location and will be looked up by the name passed in the `--chain` flag.

**Comment by Sharonbc01** [comment]
@praetoriansentry moving this task to [S4. Sequencer on Mainnet Fork 11 ](https://github.com/0xPolygonHermez/cdk-erigon/milestone/4)

**Comment by Sharonbc01** [comment]
@praetoriansentry confirmed this was successfully tested so closing this ticket
