### ISSUE TITLE
Devops monitoring & alerting to be in place for Sequencer to be deployed to mainnet.

### ISSUE THREAD

**Issue by Sharonbc01** [0xPolygon/cdk-erigon#866]
# Rationale

Why should this feature exist?
What are the use-cases?

# Implementation

Do you have ideas regarding the implementation of this feature?
Are you willing to implement this feature?

**Comment by Sharonbc01** [comment]
Hi @rekibnikufesin tagging you to this issue for v-team related to monitoring & alerting for the CDK Erigon Sequencer planned to deployed to Cardona target date Aug 12th 2024.

**Comment by rekibnikufesin** [comment]
ACK. Reference internal tickets SPEC-59 and SPEC-115

**Comment by Sharonbc01** [comment]
Can this include  Issue #1005 · 0xPolygonHermez/cdk-erigon](https://github.com/0xPolygonHermez/cdk-erigon/issues/1005)

**Comment by Sharonbc01** [comment]
WIP. @rekibnikufesin Please advise when complete.

**Comment by Sharonbc01** [comment]
Latest status:  vteam have the monitoring in place using datadog. Rafa is currently adjusting the alert threshold values used to trigger Squadcast.
In addition to that, we need to migrate the Grafana dashboards to Datadog, but that may be out of scope for this ticket.
