### ISSUE TITLE
`SpawnStageBatches` high cpu in RPC node due to tight loop

### ISSUE THREAD

**Issue by praetoriansentry** [0xPolygon/cdk-erigon#873]
#### System information

Erigon version: `beta13-candidate3`

OS & Version: `Linux straylight 6.9.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.11-1 (2024-07-25) x86_64 GNU/Linux`

Commit hash: https://github.com/0xPolygonHermez/cdk-erigon/commit/522523597f2c46ee2bfa5a001b26c6aead2addd9

Erigon Command (with flags/config): `cdk-erigon --pprof=true --pprof.addr 0.0.0.0 --config /etc/cdk-erigon/config.yaml`

Chain/Network: Local Devnet

#### Expected behaviour

When the network has no load and no transactions, I would expect that the RPC has low CPU usage because it's not executing transactions or handling any http/ws traffic

#### Actual behaviour

Even when idle, the RPC seems to always use at least 1 core at 100%. While running the RPC node, one core is always in use

![the rpc node is using 101% cpu here even though the network is just producing empty blocks](https://github.com/user-attachments/assets/94478e20-6db0-44dc-943a-0b28ff731d09)

The flamegraph here will give a sense of the activity that's causing the CPU to run while it's idle:
![cpu flame graph of idle activity](https://github.com/user-attachments/assets/715f08bb-54e4-4be2-bcfa-eb097c7161ee)

This is a similar picture if you're more familiar with this output
[profile001.pdf](https://github.com/user-attachments/files/16426303/profile001.pdf)

In order to fix this, we tested adding a small timeout in the `default` case of this `select`:
https://github.com/0xPolygonHermez/cdk-erigon/blob/beta13-candidate3/zk/stages/stage_batches.go#L375-L406

That reduces CPU pressure significantly, but there might be a better approach.

#### Steps to reproduce the behaviour

Run a devnet and it seems like the cdk-erigon node for RPC will use 100%+ cpu even when idle

**Comment by V-Staykov** [comment]
That is an okay approach. We should probably check all the select loops we have and add some timeouts to the default cases. I'll make a PR shortly.
