### ISSUE TITLE
[Sequencer] Tx pool returns `INTERNAL_ERROR: pending sub-pool is full` even if it should just update existing transactions

### ISSUE THREAD

**Issue by V-Staykov** [0xPolygon/cdk-erigon#888]
#### Expected behavior
It should update the current existing transaction and it's count should not rise.

#### Actual behavior
It throws an error like trying to add new transactions to the pool `INTERNAL_ERROR: pending sub-pool is full`

#### Steps to reproduce the behavior
1. Run a sequencer
2. Send 10 000 transactions with gas price below the limit
3. Send again the same transactions with gas price above the limit

**Comment by Sharonbc01** [comment]
Important to fix but not a priority.

**Comment by V-Staykov** [comment]
This is either fixed, or was badly tested before. It now works as expected.

**Comment by Sharonbc01** [comment]
Great thanks @V-Staykov I will close this issue now you have confirmed issue is resolved.
