### ISSUE TITLE
Error downloading blocks from datastream retries

### ISSUE THREAD

**Issue by rekibnikufesin** [0xPolygon/cdk-erigon#906]
#### System information

Erigon version: `2.43.0-dev`

OS & Version: Linux using docker `hermeznetwork/cdk-erigon:acceptance-2.0.0-beta14-candidate-92e7d22`

Commit hash: 

Erigon Command (with flags/config): `cdk-erigon --config=/app/secret/erigon.yaml`

Concensus Layer:

Concensus Layer Command (with flags/config):

Chain/Network: zkevm-testnet

#### Expected behaviour

Log: 

```
Error downloading blocks from datastream:

{
--
 
error | 10.4.4.8:45770 10.8.2.194:6900 Error sending to server: write tcp 10.4.4.8:45770->10.8.2.194:6900: write: broken pipe
lvl | eror
t | 2024-07-31T17:15:39.51007571Z
}

```
should retry on broken tcp connection

#### Actual behaviour

Appears to retry, but may need a delay before retrying to allow network issues to resolve

#### Steps to reproduce the behaviour

None

#### Backtrace

````
None
````

**Comment by mandrigin** [comment]
fixed by #910
