### ISSUE TITLE
[MockProver] new state root mismatch should halt

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#912]
Currently when the mock prover finds a `NewStateRoot` mismatch it is overwriting the value with the one found by the executor.  When we find this scenario the mock prover should halt instead.

**Comment by Sharonbc01** [comment]
Hey @hexoscott who is Polygon needs to review this issue please? Also what milestone is it related to?

**Comment by ToniRamirezM** [comment]
@hexoscott I think you understood from the logs that the SR is replaced when a mismatch is found, but this is not te case, it is replaced when a mock proof is received from the mock prover, as the mock proof contains a mock SR.

**Comment by mandrigin** [comment]
okay, so if the state root in DS is differrent from the mock proof's SR -- what will happen?

**Comment by Sharonbc01** [comment]
@ToniRamirezM can you comment in use case when using mock prover

**Comment by Sharonbc01** [comment]
Already done
