### ISSUE TITLE
[Seq-Sender] Wrong batchl2data sent to L1

### ISSUE THREAD

**Issue by ToniRamirezM** [0xPolygon/cdk-erigon#925]
In Network 8 the verification for batch 730 has the state root that matches batch 731 execution. After first analysis it looks like it may be related to the new parallel mode in the sequence sender.

**Comment by mandrigin** [comment]
okay, it seems like to be because we are sending `batch_end` incorrectly when daizy-chaining RPC nodes (datastream from RPC is incorrect, from the sequencer is correct).

**Comment by Sharonbc01** [comment]
Not listed as Critical to the release as the seq-sender sanity checks are now in place.

**Comment by Sharonbc01** [comment]
Unable reproduce

**Comment by Sharonbc01** [comment]
Unable to reproduce
