### ISSUE TITLE
[RPC] - LER for WIP batches not correct

### ISSUE THREAD

**Issue by hexoscott** [0xPolygon/cdk-erigon#933]
When querying zkevm_getBatchByNumber we read the LER for the batch which works fine for anything other than a WIP batch.  For WIP batches this LER can come back incorrectly or empty which causes a delay in the legacy node syncing from erigon as it then needs to retry the request, the retry succeeds. So the problem seems like something timing related.

Perhaps the problem is that the RWTX has not been committed yet when the call to the RPC is made so the RPC has an older view on the state and doesn't respond with the LER expected.  Just an idea at this stage that needs exploring.

**Comment by mandrigin** [comment]
Fixed in 1.2.15.4 and beta16.
