### ISSUE TITLE
Premature close batch in Bali

### ISSUE THREAD

**Issue by ToniRamirezM** [0xPolygon/cdk-erigon#934]
Batch 55667 in Bali has a different content in the data stream and in L1. It is smaller in L1.

In the following screenshot we can see that after block 4766320 the sequence-sender receives a "batch end" entry in the DS and so in closes batch 55667:

![Captura de pantalla 2024-08-07 a las 12 02 05](https://github.com/user-attachments/assets/539bab74-8843-4c39-ba8d-ccd8faa5204e)

(logs from the erigon-rpc are also shown)

2 seconds later new l2blocks for batch 55667 arrive, but the seq-sender ignores them, as the batch 55667 is already closed.

This explains why the batch in L1 is smaller than in the DS, as it lacks many l2blocks.

Current data streams from the sequencer and the RPC do not have a batch end entry after block 4766320, but they were regenerated on the August 2nd.

It looks like the rpc does and incremental handling of block, and one of this increments ends in block 4766320 (not sure if this is just a coincidence or might be related)

![Captura de pantalla 2024-08-07 a las 12 07 00](https://github.com/user-attachments/assets/5e8cfc22-b351-47c3-90fa-b2c6a707a70b)

Datadog:

https://app.datadoghq.com/logs?query=service%3Azkevm-bali%20filename%3A0.log%20source%3A%28rpc-erigon%20OR%20seqsender%29&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZD75IN_AAAXiNslZyG7BQCZ&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=time%2Cdesc&viz=&from_ts=1722212640000&to_ts=1722213000000&live=false

**Comment by mandrigin** [comment]
seems like the same as #925

**Comment by Sharonbc01** [comment]
Not listed as Critical to the release as the seq-sender sanity checks are now in place.

**Comment by Sharonbc01** [comment]
Unable to reproduce
