### ISSUE TITLE
syncTrustedState: batch[2091286/2091286] error processing trusted batch 2091286:

### ISSUE THREAD

**Issue by Sharonbc01** [0xPolygon/cdk-erigon#957]
See Datadog [logs]([https://app.datadoghq.com/logs?query=service%3Azkevm-mainnet%20source%3A%28permission[…]z=stream&from_ts=1723390442678&to_ts=1723476842678&live=true](https://app.datadoghq.com/logs?query=service%3Azkevm-mainnet%20source%3A%28permissionless2-synchronizer%20OR%20permissionless-synchronizer%29%20status%3Aerror&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZFHDcgN8fmqWQAAAAAAAAAYAAAAAEFaRkhEZEpQQUFCRXI3el9DLTJ4NmdBVgAAACQAAAAAMDE5MTQ3MTQtZmQxYy00ZDE0LWJiYjgtZDE3NTUwOTI5MTlh&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1723390442678&to_ts=1723476842678&live=true)

`syncTrustedState: batch[2091286/2091286] error processing trusted batch 2091286: incremental: Batch 2091286: processBatchResp.NewLocalExitRoot(0xe21e17686db38d357c67f689d4accc49d7916d4f4b8bae58fab044cfed7164e0) != data.StateBatch.LocalExitRoot(0xaee23fb7eaee8dcdb5ab366db0bfc6dfedbf3a139337f0a0828da977e0a9b5cc). Err: batch desynchronized
`

These are known issue that don't impede syncing. Nice to fix for release to mainnet

**Comment by revitteth** [comment]
Hopefully fixed by: https://github.com/0xPolygonHermez/cdk-erigon/pull/943

**Comment by Sharonbc01** [comment]
@revitteth what build would this fix be in for @rafael-genes to validate with?  

cc: @eduadiez

**Comment by mandrigin** [comment]
no issues with pless sync (no error logs in the last 17 hours) since this fix is deployed, closing the issue
