### ISSUE TITLE
Erigon RPC - Instances stop syncing from DS

### ISSUE THREAD

**Issue by rafael-genes** [0xPolygon/cdk-erigon#964]
#### System information

Erigon version: hermeznetwork/cdk-erigon:v1.2.15.3

Erigon Command (with flags/config): cdk-erigon --config=/app/secret/erigon.yaml 

Chain/Network: zkEVM mainnet

#### Expected behaviour
Keep syncing from Datastream.

#### Actual behaviour
It stops syncing form datastream.

#### Steps to reproduce the behaviour
TBD. From 24 instances created from scratch, only 2 of them had this problem and they already were able to sync up to the top. The problem appear randomly once is synced.

#### Backtrace

````
[datastream_client] Error downloading blocks from datastream error10.4.33.7:40278 10.8.2.241:6900 Error sending to server: write tcp 10.4.33.7:40278->10.8.2.241:6900: write: broken pipe
````

**Comment by mandrigin** [comment]
I don't think its critical for mainnet deploy, especially if an LB can remove these nodes from rotation. 2 out of 24 is not too bad. @rafael-genes btw, does it gets fixed with restart?

**Comment by V-Staykov** [comment]
We've added quite some fixes to the datastream since and te sync is more stable now. I am closing this one, please comment if it needs reopening.
