### ISSUE TITLE
[RPC] eth_getTransactionByHash returns null when TX is only in the pool

### ISSUE THREAD

**Issue by tclemos** [0xPolygon/cdk-erigon#977]
#### System information
Erigon version: `2.0.0-beta15`

Steps to reproduce.
- send a TX with a `future nonce` to the network using a `Legacy node`
- call `eth_getTransactionByHash` using an `Erigon node`

Actual Result:
- returns null

Expected Result: 
- returns the TX data with block num and block hash as null to allow the user to know the TX exist but it is not mined yet.

**Comment by hexoscott** [comment]
being handled in https://github.com/0xPolygonHermez/cdk-erigon/pull/985

**Comment by mandrigin** [comment]
fixed in https://github.com/0xPolygonHermez/cdk-erigon/pull/985
