### ISSUE TITLE
RPC - healthcheck error during sync

### ISSUE THREAD

**Issue by rafael-genes** [0xPolygon/cdk-erigon#983]
#### System information

Erigon version: v1.2.15.4

OS & Version: docker image

Commit hash: v1.2.15.4

Chain/Network: zkEVM mainnet

#### Expected behaviour
/health endpoint with header 'X-ERIGON-HEALTHCHECK: synced' returns 200 only when is completely synced.

#### Actual behaviour
/health endpoint is returning a 200 when the instance is still syncing (over 2k batches and 100k l2 blocks behind).

**Comment by rafael-genes** [comment]
As a result, the LoadBalancer is including unsynced instances and we had unconsistend data:
![image](https://github.com/user-attachments/assets/b9b14a09-b449-4dbf-8851-59286ba02722)

**Comment by V-Staykov** [comment]
This is expected behavior. It comes from the grpc library. The GRPC works since stageloop starts, so it is okay for it to show healthy state. We have other endpoints to show ifsynced.
